define({
	"m_home": "Home",
	"m_admin": "Admin",
	"m_tm": "Forms",
	"m_analysis": "Analysis",
	"m_reports": "Reports",
	"m_refresh": "Refresh",
	"m_export": "Export",
	"m_discuss": "Discuss",
	"m_modify": "Modify",
	"m_web_forms": "Web Forms",
	"m_docs": "Documentation",
	"m_monitor": "Monitoring",
	"m_user": "Users",
	"m_assign": "Tasks",
	"m_help": "Help",
	"m_forgot_password": "Forgot Password",
	"m_locations": "Locations",
	"m_section": "Section",
	"m_notify": "Notifications",
	"m_view": "View",
	"m_attach": "Load Attachments",
	"m_modules": "Modules",
	"m_open": "Open",
	"m_new": "New",
	"m_import": "Import",
	"m_calculations": "Calculations",
	
	// Smap Server
	"ss_welcome": "Welcome to Smap Server Version:",
	"ss_welcome2": "A description of changes in this release can be found here:",
	"ss_ft": "Get Field Task",
	"ss_su": "Get Smap Uploader",
	
	// Common
	"c_project": "Select Project",
	"c_forms": "Forms",
	"c_forward": "Forward",
	"c_name": "Name",
	"c_type": "Type",
	"c_file": "File",
	"c_host": "Host",
	"c_user": "User",
	"c_email": "Email",
	"c_lang": "Language",
	"c_password": "Password",
	"c_c_p": "Confirm Password",
	"c_r_p": "Reset Password",
	"c_en": "Enable",
	"c_loc_f": "Local Form:",
	"c_rem_f": "Remote Form",
	"c_rem_u": "Remote User",
	"c_enabled": "Enabled",
	"c_edit": "Edit",
	"c_del": "Delete",
	"c_download": "Download",
	"c_done": "Done",
	"c_cancel": "Cancel",
	"c_save": "Save",
	"c_close": "Close",
	"c_logout": "Logout",
	"c_block": "Block",
	"c_graph": "Graph",
	"c_map": "Map",
	"c_table": "Table",
	"c_tables": "Tables",
	"c_images": "Images",
	"c_title": "Title",
	"c_comment": "Comment",
	"c_country": "Country",
	"c_region": "Region",
	"c_district": "District",
	"c_community": "Community",
	"c_node": "Node",
	"c_relation": "Relation",
	"c_from": "From",
	"c_subject": "Subject",
	"c_to": "To",
	"c_properties": "Properties",
	"c_question": "Question",
	"c_include": "Include",
	"c_unique": "Unique",
	"c_survey": "Survey",
	"c_date": "Date",
	"c_none": "None",
	"c_hour": "Hour",
	"c_day": "Day",
	"c_week": "Week",
	"c_year": "Year",
	"c_matches": "Matches",
	"c_filter": "Filter",
	"c_inclusive": "Inclusive",
	"c_value": "Value",
	"c_clear": "Clear",
	"c_options": "Options",
	"c_data": "Data",
	"c_layers": "Layers",
	"c_settings": "Settings",
	"c_start": "Start",
	"c_back": "Back",
	"c_target": "Target",
	"c_details": "Details",
	"c_action": "Action",
	
	// File Types
	"ft": "File Type",
	"ft_xls": "XLS Form",
	"ft_xml": "XML Form",
	"ft_pdf": "PDF Form",
	
	// Template Management
	"tm_s_del": "Show deleted forms",
	"tm_d_forms": "Delete Forms",
	"tm_r_forms": "Restore Forms",
	"tm_e_forms": "Erase Forms",
	"tm_c_form": "Create a Form",
	"tm_g_temp": "Download Template",
	"tm_g_temp_i1": "Download a template to create a new form on your personal computer. When you have finished, upload it to the server by clicking on the upload button below. You will first need to select the XLS file containing the form you have created and give it a name.",
	"tm_g_temp_i3": "Reference Guide",
	"tm_g_temp_i4": "Other editors can be used including: ",
	"tm_ul_f": "Upload a Form",
	"tm_si": "Specify survey identifier",
	"tm_up": "Upload",
	"tm_add_for": "Add Forward",
	"tm_ref_f": "Refresh Form List",
	
	// Analysis
	"a_exp_title": "Export Results",
	"a_exp_leg1": "Select a survey",
	"a_exp_leg2": "Output format:",
	"a_exp_notes": "Export notes:",
	"a_exp_split": "Split lat / lon:",
	"a_sel_ways": "Select ways (if any):",
	"a_sel_forms": "Select forms to include:",
	"a_sel_model": "Edit survey model",
	"a_type": "Chart Type",
	"a_showon": "Show on",
	"a_ss": "Select survey",
	"a_sq": "Select question",
	"a_gb": "Group by",
	"a_ts": "Time series",
	"a_g_gps": "GPS coordinates within region",
	"a_fbv": "Filter by value",
	"a_from_date": "From date",
	"a_to_date": "To date",
	"a_fq": "Filter question",
	"a_res": "Please provide a reason",
	
	// Messages
	"msg_wait": "Waiting for a response from the server. Please try again in a few seconds",
	"msg_sel_survey": "You must select a survey",
	"msg_sel_q": "You must select a question to show on a graph",
	"msg_val_prot": "Protocol (http:// or https://) must be specified with the hostname",
	"msg_val_p": "A project must be selected for this form",
	"msg_val_rf": "You must select a remote form",
	"msg_val_rh": "You must select a remote host",
	"msg_val_u_id": "You must specify a user id",
	"msg_val_pass": "You must specify a password",
	"msg_val_let": "Name must start with a letter or underscore",
	"msg_add_notification": "Add Notification",
	"msg_edit_notification": "Edit Notification",
	"msg_sel_form": "Select Form:",
	"msg_sel_media": "Select Media Question:",
	"msg_err_save": "Error: Save failed: ",
	"msg_err_del": "Error: Delete failed: ",
	"msg_err_upd": "Error: Update failed: ",
	"msg_err_res": "Error: Restore failed: ",
	"msg_err_block": "Error: Block failed: ",
	"msg_err_get_f": "Error: Get forms failed: ",
	"msg_err_cert": "Remote server does not have a signed certificate, try using http:// instead of https://",
	"msg_no_edit_rep": "You cannot edit a record that has been replaced by another record",
		
	// template load errors
	"e_u_err": "Form Upload Error",
	"e_u_exists": "exists in project",
	"e_h_rename": "Change the name of the form or delete the old form",
	"e_u_sm_no_list": "select_multiple question without list name",
	"e_h_sm_no_list": "Check the survey sheet. Make sure you have specified a list name for all the select_multiple questions",
	"e_u_so_no_list": "select_one question without list name",
	"e_h_so_no_list": "Check the survey sheet. Make sure you have specified a list name for all the select_one questions",
	"e_unknown": "Unknown error",
	"e_get_help": "Contact the help desk",
	"e_calc": "Calculation error",
	"e_h_calc1": "Check the 'calculation' column for an invalid formula (A valid formula results in either true or false)",
	"e_h_calc2": "Otherwise check the 'relevant' column for a formula that does not result in a true or false result",
	"e_inv_f": "Invalid Function",
	"e_h_f1": "Check for capital letters, all letters should be lower case",
	"e_h_f2": "Check for spelling mistakes in the name of the function",
	"e_val": "Validation error",
	"e_circ": "Check for circular references",
	"e_in_q": "in question",
	"e_h_c1": "A 'relevant' statement for question is potentially referring to  itself instead of referring to another question",
	"e_h_c2": "Relevant statements are evaluated before a question is asked so they cannot refer to their own questions",
	"e_brackets": "Mismatched brackets in function",
	"e_text": "Error with the following text:"
		
	
		
	
		
});
