define({
	"m_home": "Home",
	"m_admin": "Admin",
	"m_tm": "Form Management",
	"m_analysis": "Analysis",
	"m_reports": "Reports",
	"m_refresh": "Refresh",
	"m_export": "Export",
	"m_discuss": "Discuss",
	"m_modify": "Modify",
	"m_web_forms": "Web Forms",
	"m_docs": "Documentation",
	"m_monitor": "Monitoring",
	"m_user": "Users",
	"m_assign": "Tasks",
	"m_help": "Help",
	"m_forgot_password": "Forgot Password",
	
	// Smap Server
	"ss_welcome": "Welcome to Smap Server Version:",
	"ss_welcome2": "A description of changes in this release can be found here:",
	"ss_ft": "Get Field Task",
	"ss_su": "Get Smap Uploader",
	
	// Common
	"c_project": "Select Project",
	"c_forms": "Forms",
	"c_forward": "Forward",
	"c_name": "Namexx",
	"c_type": "Typexx",
	"c_file": "File",
	"c_host": "Host",
	"c_user": "User",
	"c_email": "Email",
	"c_lang": "Language",
	"c_password": "Password",
	"c_c_p": "Confirm Password",
	"c_r_p": "Reset Password",
	"c_en": "Enable",
	"c_loc_f": "Local Form:",
	"c_rem_f": "Remote Form",
	"c_rem_u": "Remote User",
	"c_enabled": "Enabled",
	"c_edit": "Edit",
	"c_del": "Delete",
	"c_download": "Download",
	"c_done": "Done",
	"c_cancel": "Cancel",
	"c_save": "Save",
	"c_block": "Block",
	"c_graph": "Graphxx",
	"c_map": "Mapxx",
	"c_table": "Tablexx",
	"c_images": "Imagesxx",
	"c_title": "Title",
	"c_comment": "Comment",
	"c_country": "Country",
	"c_region": "Region",
	"c_district": "District",
	"c_community": "Community",
	"c_node": "Nodexx",
	"c_relation": "Relationxx",
	"c_from": "Fromxx",
	"c_to": "Toxx",
	"c_properties": "Propertiesxx",
	"c_question": "Questionxx",
	"c_include": "Includexx",
	"c_unique": "Uniquexx",
	"c_survey": "Surveyxx",
	"c_date": "Datexx",
	"c_none": "Nonexx",
	"c_hour": "Hourxx",
	"c_day": "Dayxx",
	"c_week": "Weekxx",
	"c_year": "Yearxx",
	"c_matches": "Matchesxx",
	"c_filter": "Filterxx",
	"c_inclusive": "Inclusivexx",
	"c_value": "Valuexx",
	"c_clear": "Clearxx",
	
	// File Types
	"ft_xls": "XLS Form",
	"ft_xml": "XML Form",
	"ft_pdf": "PDF Form",
	
	// Template Management
	"tm_s_del": "Show deleted forms",
	"tm_d_forms": "Delete Forms",
	"tm_r_forms": "Restore Forms",
	"tm_e_forms": "Erase Forms",
	"tm_c_form": "Create a Form",
	"tm_g_temp": "Download Template",
	"tm_g_temp_i1": "Download a template to create a new form on your personal computer. When you have finished, upload it to the server by clicking on the upload button below. You will first need to select the XLS file containing the form you have created and give it a name.",
	"tm_g_temp_i3": "Reference Guide",
	"tm_g_temp_i4": "Other editors can be used including: ",
	"tm_ul_f": "Upload a Form",
	"tm_si": "Specify survey identifier",
	"tm_up": "Upload",
	"tm_add_for": "Add Forward",
	"tm_ref_f": "Refresh Form List",
	
	// Analysis
	"a_exp_title": "Export Results",
	"a_exp_leg1": "Select a form",
	"a_exp_leg2": "Output format:",
	"a_exp_notes": "Export notes:",
	"a_exp_split": "Split lat / lon:",
	"a_sel_ways": "Select ways (if any):",
	"a_sel_forms": "Select forms to include:",
	"a_sel_model": "Edit survey model",
	"a_type": "Chart Typexx",
	"a_showon": "Show onxx",
	"a_ss": "Select surveyxx",
	"a_sq": "Select questionxx",
	"a_gb": "Group byxx",
	"a_ts": "Time seriesxx",
	"a_g_gps": "GPS coordinates within regionxx",
	"a_fbv": "Filter by valuexx",
	"a_from_date": "From datexx",
	"a_to_date": "To datexx",
	"a_fq": "Filter questionxx",
	
	// Messages
	"msg_wait": "Waiting for a response from the server. Please try again in a few seconds",
	"msg_sel_survey": "You must select a survey",
	"msg_sel_q": "You must select a question to show on a graph",
	"msg_val_prot": "Protocol (http:// or https:// must be specified with the hostname",
	"msg_val_p": "A project must be selected for this form",
	"msg_val_rf": "You must select a remote form",
	"msg_val_rh": "You must select a remote host",
	"msg_val_u_id": "You must specify a user id",
	"msg_val_pass": "You must specify a password",
	"msg_val_let": "Name must start with a letter or underscore",
	"msg_add_forward": "Add forward",
	"msg_edit_forward": "Edit forward",
	"msg_sel_form": "Select Form:",
	"msg_err_save": "Error: Save failed: ",
	"msg_err_del": "Error: Delete failed: ",
	"msg_err_res": "Error: Restore failed: ",
	"msg_err_block": "Error: Block failed: ",
	"msg_err_get_f": "Error: Get forms failed: ",
	"msg_err_cert": "Remote server does not have a signed certificate, try using http:// instead of https://"
});
