define(
{
    "m_home": "Inicio",
    "m_admin": "Admin",
    "m_tm": "Formulários",
    "m_analysis": "Análises",
    "m_reports": "Relatórios",
    "m_refresh": "Atualizar",
    "m_export": "Exportar",
    "m_discuss": "Opinião",
    "m_modify": "Modificar",
    "m_web_forms": "Formulários On-Line",
    "m_docs": "Documentação",
    "m_monitor": "Monitorização",
    "m_user": "Utilizadores",
    "m_assign": "Tarefas",
    "m_help": "Ajuda",
    "m_forgot_password": "Recuperar Palavra-Chave",
    "m_register": "Criar Conta",
    "m_locations": "Locais",
    "m_section": "Secção",
    "m_notify": "Notificações",
    "m_view": "Visualizar",
    "m_attach": "Carregar Anexos",
    "m_modules": "Módulos",
    "m_open": "Abrir",
    "m_new": "Novo",
    "m_import": "Importar",
    "m_calculations": "Cálculos",
    "m_resources": "Recursos Partilhados",
    "m_review": "Rever",
    "ss_welcome": "Bem Vindo ao Servidor SMAP Versão:",
    "ss_welcome2": "Alterações nesta versão",
    "ss_ft": "Descarregar Field Task",
    "ss_su": "Descarregar Smap Uploader",
    "c_desc": "Descrição",
    "c_project": "Selecione Projeto",
    "c_forms": "Formulários",
    "c_forward": "Reencaminhar",
    "c_forwarded": "Reencaminhado",
    "c_name": "Nome",
    "c_company_name": "Nome Empresa",
    "c_type": "Tipo",
    "c_file": "Ficheiro",
    "c_host": "Servidor",
    "c_user": "Utilizador",
    "c_email": "Correio Electrónico",
    "c_lang": "Linguagem",
    "c_langs": "Linguagens",
    "c_orientation": "Orientação",
    "c_password": "Palavra-Chave",
    "c_c_p": "Confirme Palavra-Chave",
    "c_r_p": "Limpar Palavra-Chave",
    "c_en": "Ativar",
    "c_loc_f": "Form. Local:",
    "c_rem_f": "Form. Remoto",
    "c_rem_u": "Utilizador Remoto",
    "c_enabled": "Ativo",
    "c_edit": "Editar",
    "c_del": "Eliminar",
    "c_download": "Descarregar",
    "c_done": "Efetuado",
    "c_cancel": "Cancelar",
    "c_save": "Gravar",
    "c_submit": "Submeter",
    "c_submitted": "Submetido",
    "c_test": "Testar",
    "c_validate": "Validar",
    "c_close": "Fechar",
    "c_logout": "Terminar Sessão",
    "c_block": "Bloquear",
    "c_graph": "Gráfico",
    "c_map": "Mapa",
    "c_map_layers": "Camadas do Mapa",
    "c_table": "Tabela",
    "c_tables": "Tabelas",
    "c_images": "Imagens",
    "c_title": "Titulo",
    "c_comment": "Comentário",
    "c_country": "País",
    "c_region": "Região",
    "c_district": "Distrito",
    "c_community": "Comunidade",
    "c_node": "Nó",
    "c_relation": "Relação",
    "c_from": "De",
    "c_subject": "Assunto",
    "c_to": "Para",
    "c_properties": "Propriedades",
    "c_question": "Questão",
    "c_include": "Incluir",
    "c_unique": "Único",
    "c_survey": "Questionário",
    "c_date": "Data",
    "c_none": "Nenhum",
    "c_hour": "Hora",
    "c_day": "Dia",
    "c_week": "Semana",
    "c_month": "Mês",
    "c_year": "Ano",
    "c_matches": "Correspondências",
    "c_filter": "Filtro",
    "c_inclusive": "Inclusivé",
    "c_value": "Valor",
    "c_clear": "Limpar",
    "c_options": "Opções",
    "c_data": "Informação",
    "c_layers": "Camadas",
    "c_settings": "Definições",
    "c_start": "Início",
    "c_back": "Anterior",
    "c_target": "Acção",
    "c_content": "Conteudo",
    "c_attach": "Anexar",
    "c_details": "Detalhes",
    "c_action": "Acção",
    "c_mapid": "Id. do Mapa",
    "c_zoom": "Niveis do Zoom",
    "c_zoom_data": "Zoom aos dados",
    "c_vector_data": "Dados do vector",
    "c_vector_style": "Estilo do vector",
    "c_portrait": "Vertical",
    "c_landscape": "Horizontal",
    "c_tools": "Ferramentas",
    "c_required": "Colocar como obrigatório",
    "c_not_required": "Colocar como opcional",
    "c_del_sel": "Eliminar seleccionados",
    "c_print": "Imprimir",
    "c_repeat": "Repetir",
    "c_scheduled": "Agendado",
    "c_t_c": "Termos e condições",
    "c_agree": "Eu concordo com o",
    "c_select": "Seleccionar",
    "c_status": "Estado",
    "c_coords": "Coordenadas",
    "c_task": "Tarefa",
    "c_rec": "(Recomendado)",
    "c_source": "Origem",
    "c_show": "Mostrar",
    "c_hide": "Esconder",
    "c_totals": "Totais",
    "c_instances": "Instâncias",
    "c_device": "Dispositivo",
    "c_success": "Sucesso",
    "c_errors": "Erros",
    "c_error": "Erro",
    "c_lt": "Hora local",
    "c_location": "Localização",
    "c_ident": "Identificador",
    "c_version": "Versão",
    "ft": "Tipo de ficheiro",
    "ft_xls": "Form. XLS",
    "ft_xml": "Form. XML",
    "ft_codebook": "Codebook",
    "ft_pdf": "Modelo PDF",
    "tm_s_del": "Mostrar form. eliminados",
    "tm_d_forms": "Eliminar formulários",
    "tm_r_forms": "Recuperar formulários",
    "tm_e_forms": "Apagar formulários",
    "tm_c_form": "Criar formulário",
    "tm_c_xls": "Usando o editor de folha de cálculo",
    "tm_g_temp": "Descarregar Modelo",
    "tm_g_new": "Criar novo formulário",
    "tm_g_temp_i1": "Descarregue o modelo para criar um novo formulário no seu computador. Quando terminar, envie-o para o servidor usando o botão de envio de formulário em baixo. Terá de selecionar primeiro o ficheiro XLS que contém o formulário que criou e dar-lhe um nome.",
    "tm_g_temp_i3": "Guia de Referência",
    "tm_g_temp_i4": "Pode usar outros editores incluindo:",
    "tm_ul_f": "Enviar a folha de cálculo",
    "tm_si": "Indique o identificador do questionário",
    "tm_up": "Enviar modelo",
    "tm_add_for": "Adicionar reencaminhamento",
    "tm_ref_f": "Atualizar lista de Formulários",
    "a_exp_title": "Exportar Resultados",
    "a_exp_leg1": "Seleccione um questionário",
    "a_exp_leg2": "Formato:",
    "a_exp_notes": "Exportar notas:",
    "a_exp_split": "lat / lon separadas:",
    "a_exp_merge": "Comprimir vários:",
    "a_sel_ways": "Selecione caminhos (se existirem):",
    "a_sel_forms": "Selecione formulários para incluir:",
    "a_sel_model": "Editar o modelo do questionário",
    "a_type": "Tipo de Gráfico",
    "a_showon": "Mostrar em",
    "a_ss": "Selecione questionário",
    "a_sq": "Selecione questão",
    "a_gb": "Agrupar por",
    "a_ts": "Séries de tempo",
    "a_g_gps": "Coordenadas GPS na região",
    "a_fbv": "Filtrar por valor",
    "a_from_date": "Data de",
    "a_to_date": "Até data",
    "a_fq": "Questão a filtrar",
    "a_res": "Por favor, indique uma razão",
    "msg_wait": "A aguardar uma resposta do servidor. Por favor, tente novamente dentro de alguns segundos",
    "msg_reason": "Por favor, indique uma razão:",
    "msg_sel_survey": "Tem de seleccionar um questionário",
    "msg_sel_q": "Tem de seleccionar uma questão para mostrar no gráfico",
    "msg_val_prot": "Tem de especificar o protocolo (http:// ou https://) juntamente com o nome do servidor",
    "msg_val_p": "Tem de selecionar um projecto para este formulário",
    "msg_val_rf": "Tem de selecionar um form. remoto",
    "msg_val_rh": "Tem de selecionar um servidor remoto",
    "msg_val_u_id": "Tem de indicar o utilizador",
    "msg_val_pass": "Tem de indicar a palavra-chave",
    "msg_val_let": "O nome tem de começar por uma letra ou underscore",
    "msg_add_notification": "Adicionar Notificação",
    "msg_edit_notification": "Alterar notificação",
    "msg_add_map": "Adicionar Mapa",
    "msg_edit_map": "Alterar Mapa",
    "msg_sel_form": "Selecione Formulário:",
    "msg_sel_media": "Seleccione a pergunta multimédia:",
    "msg_err_save": "Erro: A gravação falhou:",
    "msg_err_del": "Erro: A eliminação falhou:",
    "msg_err_upd": "Erro: Actualização falhou:",
    "msg_err_res": "Erro: A recuperação falhou:",
    "msg_err_block": "Erro: O bloqueio falhou:",
    "msg_err_get_f": "Erro: A leitura dos formulários falhou:",
    "msg_err_wait": "Expirou o tempo de espera do servidor ou não existem perguntas neste projecto para atribuir a um utilizador. Se o projecto tem perguntas, então tente novamente dentro de alguns segundos",
    "msg_err_cert": "O servidor remoto não contém um certificado válido, tente usar http:// em vez de https://",
    "msg_no_edit_rep": "Não pode alterar um registo que foi substituido por outro.",
    "msg_confirm_del": "Tem a certeza que deseja eliminar",
    "msg_confirm_tasks": "este grupo e todas as suas tarefas?",
    "msg_n_v": "Inválido",
    "e_b_e": "Baseado num questionário existente",
    "e_s_r": "Guardar resultados numa tabela partilhada",
    "t_complete": "Mostrar Tarefas Concluidas",
    "t_show": "Mostrar tarefas para:",
    "t_assign": "Atribuir utilizador",
    "t_add_group": "Adicionar grupo de tarefas",
    "t_lt_file": "Carregar tarefas a partir de um ficheiro",
    "t_choose_user": "Escolha o utilizador a atribuir às tarefas seleccionadas",
    "t_ce": "Limpar tarefas existentes",
    "t_ce_warn": "Isto irá limpar todos os dados no questionário. Tem a certeza que deseja continuar?",
    "t_ceg": "Criar grupo de tarefas vazio",
    "t_ep": "Projecto existente",
    "t_es": "Questionário existente",
    "t_ns": "Novo Questionário",
    "t_ft": "Filtrar tarefas",
    "t_fq": "Filtrar por pergunta",
    "t_so": "Opção seleccionada",
    "t_sn": "Indique valor numérico",
    "t_st": "Indique valor de texto",
    "t_ue": "Actualizar resultados actuais",
    "t_ap": "Parâmetros de morada",
    "t_nfc": "Localização ou NFC",
    "t_assigned": "Atribuido",
    "t_fl": "Ficheiro enviado",
    "t_efnl": "Erro: o ficheiro não foi enviado",
    "t_add_tasks": "Clique no mapa onde deseja adicionar novas tarefas. Quando terminar clique no botão \"Guardar Tarefas\"",
    "t_add_tasks2": "Adicionar Tarefas",
    "t_save_tasks": "Guardar Tarefas",
    "e_u_err": "Erro ao enviar o formulário",
    "e_u_exists": "existe no projecto",
    "e_h_rename": "Mude o nome do formulário ou elimine o antigo",
    "e_u_sm_no_list": "questão do tipo \"select_multiple\" sem indicação do nome da lista de valores",
    "e_h_sm_no_list": "Verifique as definições do formulário. Confirme que indicou o nome da lista de valores para todas as questões do tipo \"select_multiple\"",
    "e_u_so_no_list": "questão do tipo \"select_one\" sem indicação do nome da lista de valores",
    "e_h_so_no_list": "Verifique as definições do formulário. Confirme que indicou o nome da lista de valores para todas as questões do tipo \"select_one\"",
    "e_unknown": "Erro desconhecido",
    "e_get_help": "Contacte o serviço de assistência técnica",
    "e_calc": "Erro ao calcular formulas",
    "e_h_calc1": "Verifique a coluna \"calculation\" por formulas inválidas (uma formula válida retorna o valor verdadeiro ou falso)",
    "e_h_calc2": "Ou então verifique a coluna \"relevant\" por uma formula que não retorne um valor verdadeiro ou falso",
    "e_inv_f": "Função inválida",
    "e_h_f1": "Confirme que todas as letras estão em minusculas",
    "e_h_f2": "Verifique que não existam erros ortográficos no nome da função",
    "e_val": "Erro de validação",
    "e_circ": "Procure por referências circulares",
    "e_in_q": "na questão",
    "e_h_c1": "Possivelmente existe uma condição \"relevant\" que está a validar-se a si mesma em vez de outra questão ",
    "e_h_c2": "Condições do tipo \"relevant\" são avaliadas antes da questão ser apresentada, pelo que não podem fazer referência à sua própria questão",
    "e_brackets": "Número impar de parentesis na função",
    "e_text": "Erro com o seguinte texto:",
    "r_o_n": "Nome da Organização",
    "r_y_n": "O seu nome",
    "r_y_e": "O seu e-mail",
    "r_y_o": "Website da Organização",
    "r_f": "Formulário de registo",
    "mon_l200": "(últimos 200)",
    "mon_gtb": "Agrupar totais por",
    "mon_nl": "Não foi carregado",
    "mon_dup": "Duplicados",
    "mon_att": "Anexos extra",
    "mon_sa": "Mostrar como",
    "mon_zoom_grid": "Zoom às grelhas",
    "mon_show_grid": "Mostrar grelhas",
    "mon_clear_grid": "Limpar grelhas",
    "mon_create_grid": "Criar grelha",
    "mon_del_grid": "Eliminar grelha",
    "mon_sel_layer": "Seleccione uma camada a adicionar ao mapa como sobreposição",
    "mon_c_reg": "Criar uma nova região",
    "mon_c_reg_i": "Indique um nome para a região e a largura de cada célula em metros. Clique no mapa para definir o centro de uma das células. Mantenha a tecla \"SHIFT\" pressionada e arraste o rato para definir os limites.",
    "mon_name_cond": "(minusculas, sem espaços ou números)",
    "mon_cw": "Largura da Célula (em metros, maior que 10)",
    "mon_centre": "Centro: (clique no mapa)",
    "mon_bounds": "Limite: (clique e arraste no mapa com a tecla \"SHIFT\" pressionada)",
    "mon_sel_del": "Seleccione as regiões que deseja eliminar",
    "mon_ud": "Data de envio",
    "mon_pi": "Id. Telefone",
    "mon_fr": "Razão da falha",
    "mon_file": "Ficheiro com resultados brutos",
    "an_auth": "Autor",
    "an_published": "Publicado",
    "an_dr": "Intervalo de datas",
    "an_csel": "Limpar selecção",
    "Upload Time": "Enviar",
    "_start": "Hora Inicial",
    "_end": "Hora Final"
});