define(
{
    "m_home": "Inicio",
    "m_admin": "Admin",
    "m_tm": "Gerir Formulários",
    "m_analysis": "Análises",
    "m_reports": "Relatórios",
    "m_refresh": "Atualizar",
    "m_export": "Exportar",
    "m_discuss": "Opinião",
    "m_modify": "Modificar",
    "m_web_forms": "Formulários On-Line",
    "m_docs": "Documentação",
    "m_monitor": "Monitorização",
    "m_user": "Utilizadores",
    "m_assign": "Tarefas",
    "m_help": "Ajuda",
    "m_forgot_password": "Recuperar Palavra-Chave",
    "ss_welcome": "Bem Vindo ao Servidor SMAP Versão:",
    "ss_welcome2": "A descrição das alterações nesta versão podem ser encontradas aqui",
    "ss_ft": "Descarregar Field Task",
    "ss_su": "Descarregar Smap Uploader",
    "c_project": "Selecione Projeto",
    "c_forms": "Formulários",
    "c_forward": "Reencaminhar",
    "c_name": "Nome",
    "c_type": "Tipo",
    "c_file": "Ficheiro",
    "c_host": "Servidor",
    "c_user": "Utilizador",
    "c_email": "Correio Electrónico",
    "c_lang": "Linguagem",
    "c_password": "Palavra-Chave",
    "c_c_p": "Confirme Palavra-Chave",
    "c_r_p": "Limpar Palavra-Chave",
    "c_en": "Ativar",
    "c_loc_f": "Form. Local:",
    "c_rem_f": "Form. Remoto",
    "c_rem_u": "Utilizador Remoto",
    "c_enabled": "Ativo",
    "c_edit": "Editar",
    "c_del": "Eliminar",
    "c_download": "Descarregar",
    "c_done": "Efetuado",
    "c_cancel": "Cancelar",
    "c_save": "Gravar",
    "c_block": "Bloquear",
    "c_graph": "Gráfico",
    "c_map": "Mapa",
    "c_table": "Tabela",
    "c_tables": "Tabelas",
    "c_images": "Imagens",
    "c_title": "Titulo",
    "c_comment": "Comentário",
    "c_country": "País",
    "c_region": "Região",
    "c_district": "Distrito",
    "c_community": "Comunidade",
    "c_node": "Nó",
    "c_relation": "Relação",
    "c_from": "De",
    "c_to": "Para",
    "c_properties": "Propriedades",
    "c_question": "Questão",
    "c_include": "Incluir",
    "c_unique": "Único",
    "c_survey": "Questionário",
    "c_date": "Data",
    "c_none": "Nenhum",
    "c_hour": "Hora",
    "c_day": "Dia",
    "c_week": "Semana",
    "c_year": "Ano",
    "c_matches": "Correspondências",
    "c_filter": "Filtro",
    "c_inclusive": "Inclusivé",
    "c_value": "Valor",
    "c_clear": "Limpar",
    "c_options": "Opções",
    "c_data": "Informação",
    "c_layers": "Camadas",
    "c_settings": "Definições",
    "c_start": "Início",
    "ft_xls": "Form. XLS",
    "ft_xml": "Form. XML",
    "ft_pdf": "Form. PDF",
    "tm_s_del": "Mostrar form. eliminados",
    "tm_d_forms": "Eliminar formulários",
    "tm_r_forms": "Recuperar formulários",
    "tm_e_forms": "Apagar formulários",
    "tm_c_form": "Criar formulário",
    "tm_g_temp": "Descarregar Modelo",
    "tm_g_temp_i1": "Descarregue o modelo para criar um novo formulário no seu computador. Quando terminar, envie-o para o servidor usando o botão de envio de formulário em baixo. Terá de selecionar primeiro o ficheiro XLS que contém o formulário que criou e dar-lhe um nome.",
    "tm_g_temp_i3": "Guia de Referência",
    "tm_g_temp_i4": "Pode usar outros editores incluindo:",
    "tm_ul_f": "Envie um formulário",
    "tm_si": "Indique o identificador do questionário",
    "tm_up": "Enviar",
    "tm_add_for": "Adicionar reencaminhamento",
    "tm_ref_f": "Atualizar lista de Formulários",
    "a_exp_title": "Exportar Resultados",
    "a_exp_leg1": "Selecione um formulário",
    "a_exp_leg2": "Formato:",
    "a_exp_notes": "Exportar notas:",
    "a_exp_split": "lat / lon separadas:",
    "a_sel_ways": "Selecione caminhos (se existirem):",
    "a_sel_forms": "Selecione formulários para incluir:",
    "a_sel_model": "Editar o modelo do questionário",
    "a_type": "Tipo de Gráfico",
    "a_showon": "Mostrar em",
    "a_ss": "Selecione questionário",
    "a_sq": "Selecione questão",
    "a_gb": "Agrupar por",
    "a_ts": "Séries de tempo",
    "a_g_gps": "Coordenadas GPS na região",
    "a_fbv": "Filtrar por valor",
    "a_from_date": "Data de",
    "a_to_date": "Até data",
    "a_fq": "Questão a filtrar",
    "msg_wait": "A aguardar uma resposta do servidor. Por favor, tente novamente dentro de alguns segundos",
    "msg_sel_survey": "Tem de seleccionar um questionário",
    "msg_sel_q": "Tem de seleccionar uma questão para mostrar no gráfico",
    "msg_val_prot": "Tem de especificar o protocolo (http:// ou https:// com o servidor",
    "msg_val_p": "Tem de selecionar um projecto para este formulário",
    "msg_val_rf": "Tem de selecionar um form. remoto",
    "msg_val_rh": "Tem de selecionar um servidor remoto",
    "msg_val_u_id": "Tem de indicar o utilizador",
    "msg_val_pass": "Tem de indicar a palavra-chave",
    "msg_val_let": "O nome tem de começar por uma letra ou underscore",
    "msg_add_forward": "Adicionar reencaminhamento",
    "msg_edit_forward": "Editar reencaminhamento",
    "msg_sel_form": "Selecione Formulário:",
    "msg_err_save": "Erro: A gravação falhou:",
    "msg_err_del": "Erro: A eliminação falhou:",
    "msg_err_res": "Erro: A recuperação falhou:",
    "msg_err_block": "Erro: O bloqueio falhou:",
    "msg_err_get_f": "Erro: A leitura dos formulários falhou:",
    "msg_err_cert": "O servidor remoto não contém um certificado válido, tente usar http:// em vez de https://"
});