define(
{
    "m_home": "Accueil",
    "m_admin": "Administrer",
    "m_tm": "Formulaires",
    "m_analysis": "Analyser",
    "m_reports": "Rapports",
    "m_refresh": "Actualiser",
    "m_export": "Exporter",
    "m_discuss": "Discuter",
    "m_modify": "Modifier",
    "m_web_forms": "Formulaires Web",
    "m_docs": "Documentation",
    "m_monitor": "Surveillance",
    "m_user": "Utilisateurs",
    "m_assign": "Taches",
    "m_help": "Aide",
    "m_forgot_password": "Mot de Passe Oublié",
    "m_register": "Enregistrer",
    "m_locations": "Locations",
    "m_section": "Section",
    "m_notify": "Notifications",
    "m_view": "Affichage",
    "m_attach": "Charger Pièces Jointes",
    "m_modules": "Modules",
    "m_open": "Ouvrir",
    "m_new": "Nouveau",
    "m_import": "Importer",
    "m_calculations": "Calculer",
    "m_resources": "Ressources Partagées",
    "m_review": "Revue",
    "ss_welcome": "Bienvenu dans Smap Server Version:",
    "ss_welcome2": "Changements dans cette version",
    "ss_ft": "Obtenir Field Task",
    "ss_su": "Obtenir Smap Uploader",
    "c_desc": "Description",
    "c_project": "Sélectionné un Projet",
    "c_forms": "Formulaires",
    "c_forward": "Transférer",
    "c_forwarded": "Transferer",
    "c_name": "Nom",
    "c_company_name": "Nom de Compagnie",
    "c_type": "Type",
    "c_file": "Fichier",
    "c_host": "Hôte",
    "c_user": "Utilisateur",
    "c_email": "Email",
    "c_lang": "Langage",
    "c_langs": "Langages",
    "c_orientation": "Orientation",
    "c_password": "Mot de Passe",
    "c_c_p": "Confirmer Mot de Passe",
    "c_r_p": "Réinitialiser Mot de Passe",
    "c_en": "Activer",
    "c_loc_f": "Formulaire Local:",
    "c_rem_f": "Formulaire Distant:",
    "c_rem_u": "Utilisateur Distant",
    "c_enabled": "Activé",
    "c_edit": "Editer",
    "c_del": "Supprimer",
    "c_download": "Télécharger",
    "c_done": "Terminer",
    "c_cancel": "Annuler ",
    "c_save": "Sauvegarder ",
    "c_submit": "envoyer",
    "c_submitted": "Envoyé",
    "c_test": "Teste",
    "c_validate": "Valider",
    "c_close": "Fermer",
    "c_logout": "Déconnexion",
    "c_block": "Bloquer",
    "c_graph": "Graphique",
    "c_map": "Carte",
    "c_map_layers": "Couche de Cartes",
    "c_table": "Tableau",
    "c_tables": "Tableaux",
    "c_images": "Images",
    "c_title": "Titre",
    "c_comment": "Commentaire",
    "c_country": "Pays",
    "c_region": "Région",
    "c_district": "District",
    "c_community": "Communauté",
    "c_node": "Noeud",
    "c_relation": "Relation",
    "c_from": "A partir de",
    "c_subject": "Sujet",
    "c_to": "Vers",
    "c_properties": "Propriétés ",
    "c_question": "Question",
    "c_include": "Inclure",
    "c_unique": "Unique",
    "c_survey": "Enquête",
    "c_date": "Date",
    "c_none": "Aucun",
    "c_hour": "Heure",
    "c_day": "Jour",
    "c_week": "Semaine",
    "c_month": "Mois",
    "c_year": "Année",
    "c_matches": "Correspondances",
    "c_filter": "Filtre",
    "c_inclusive": "Inclusive",
    "c_value": "Valeur",
    "c_clear": "Effacer",
    "c_options": "Options",
    "c_data": "Donnée",
    "c_layers": "Couches",
    "c_settings": "Paramettres",
    "c_start": "Commencer",
    "c_back": "Arriere",
    "c_target": "Cible",
    "c_content": "Contenu",
    "c_attach": "joint",
    "c_details": "Détails",
    "c_action": "Action",
    "c_mapid": "ID de Carte",
    "c_zoom": "Niveaux Zoom ",
    "c_zoom_data": "Zoom de Données ",
    "c_vector_data": "Données Vecteur",
    "c_vector_style": "Style Vecteur",
    "c_portrait": "Portrait",
    "c_landscape": "Paysage",
    "c_tools": "Outils",
    "c_required": "Rendre Obligatoire",
    "c_not_required": "Rendre non Obligatoire",
    "c_del_sel": "Supprimer Selection",
    "c_print": "Imprimer",
    "c_repeat": "Repeter",
    "c_scheduled": "Planifier",
    "c_t_c": "Termes et Conditions",
    "c_agree": "J'accepte la",
    "c_select": "Selection",
    "c_status": "Statut",
    "c_coords": "Coordonnés",
    "c_task": "tâche",
    "c_rec": "(Recommandé)",
    "c_source": "Source",
    "c_show": "Afficher",
    "c_hide": "Cacher",
    "c_totals": "Total",
    "c_instances": "Instances",
    "c_device": "outil",
    "c_success": "Succés",
    "c_errors": "Erreurs",
    "c_error": "Erreur",
    "c_lt": "Heure Locale",
    "c_location": "Location",
    "c_ident": "Identifier",
    "c_version": "Version",
    "ft": "Type de Fichier",
    "ft_xls": "Formulaire XLS",
    "ft_xml": "Formulaire XML",
    "ft_codebook": "Codebook",
    "ft_pdf": "PDF Template",
    "tm_s_del": "Afficher les Formulaires Supprimer ",
    "tm_d_forms": "Supprimer Formulaires",
    "tm_r_forms": "Restaurer Formulaires",
    "tm_e_forms": "Effacer Formulaires",
    "tm_c_form": "Créer un Formulaire",
    "tm_c_xls": "Utilisant l'éditeur Spreadsheet",
    "tm_g_temp": "Télécharger Template ",
    "tm_g_new": "Créer Nouveau Formulaire",
    "tm_g_temp_i1": "Téléchargez un modèle pour créer un nouveau formulaire sur votre ordinateur personnel. Lorsque vous avez terminé, le télécharger sur le serveur en cliquant sur ​​le bouton de Charger ci-dessous. Vous devrez tout d'abord sélectionner le fichier XLS contenant le formulaire que vous avez créé et lui donner un nom",
    "tm_g_temp_i3": "Guide de Référence ",
    "tm_g_temp_i4": "Autres éditeurs peuvent être utilisés, y compris:",
    "tm_ul_f": "Charger le Spreadsheet",
    "tm_si": "Spécifiez identifiant de l'enquête",
    "tm_up": "Charger Template",
    "tm_add_for": "Ajouter Transfert",
    "tm_ref_f": "Actualiser Liste de Formulaires",
    "a_exp_title": "Exporter Resultats",
    "a_exp_leg1": "Sélectionner une enquête",
    "a_exp_leg2": "Format de Sortie",
    "a_exp_notes": "Exporter Notes",
    "a_exp_split": "Découper Lat/Long:",
    "a_exp_merge": "Compresser sélectionner multiples : ",
    "a_sel_ways": "Sélectionner Chemin (Si dispo) ",
    "a_sel_forms": "Sélectionner formulaire à inclure",
    "a_sel_model": "Editer modèle d'enquête ",
    "a_type": "Type de Graph",
    "a_showon": "Afficher dans",
    "a_ss": "Sélectionner enquête",
    "a_sq": "Sélectionner Question",
    "a_gb": "Grouper par ",
    "a_ts": "Séries de temps",
    "a_g_gps": "Les coordonnées GPS à l'intérieur de la région",
    "a_fbv": "Filtre par valeur",
    "a_from_date": "A partir de la date",
    "a_to_date": "A la date",
    "a_fq": "Filtrer question",
    "a_res": "SVP donner une raison",
    "msg_wait": "Attente de la réponse du serveur. Réessayez dans quelques secondes",
    "msg_reason": "SVP donner une raison",
    "msg_sel_survey": "Vous devez sélectionner une enquête",
    "msg_sel_q": "Vous devez sélectionner une question à afficher sur un graph",
    "msg_val_prot": "Protocol (http:// ou https://) doit être spécifié avec le nom d'hôte",
    "msg_val_p": "Un Projet doit être sélectionné pour ce formulaire",
    "msg_val_rf": "Vous devez sélectionner un formulaire distant",
    "msg_val_rh": "Vous devez sélectionner un hôte distant",
    "msg_val_u_id": "Vous devez spécifier un ID utilisateur",
    "msg_val_pass": "Vous devez spécifier un mot de passe",
    "msg_val_let": "Nom doit commencer par une lettre ou underscore",
    "msg_add_notification": "Ajouter Notification",
    "msg_edit_notification": "Editer Notification",
    "msg_add_map": "Ajouter Carte",
    "msg_edit_map": "Editer Carte",
    "msg_sel_form": "Sélectionner Formulaire:",
    "msg_sel_media": "Sélectionner question Media :",
    "msg_err_save": "Erreur: Sauvegarde Echouée:",
    "msg_err_del": "Erreur: Suppression Echouée:",
    "msg_err_upd": "Erreur: Mise à jour échouée:",
    "msg_err_res": "Erreur: Restauration Echouée:",
    "msg_err_block": "Erreur: Blocage Echoué: ",
    "msg_err_get_f": "Erreur: Obtenir Formulaires Echoué:",
    "msg_err_wait": "Soit attente du serveur ou pas d'enquête dans ce projet à assigner à l'utilisateur. Si le projet n'as pas d'enquête alors essayer encore dans quelques secondes. ",
    "msg_err_cert": "Le serveur distant ne dispose pas d'un certificat signé, essayez d'utiliser http: // au lieu de https: //",
    "msg_no_edit_rep": "Vous ne pouvez pas éditer un enregistrement déjà remplacé par un autre enregistrement.",
    "msg_confirm_del": "Etes vous sur de vouloir supprimer",
    "msg_confirm_tasks": "Ce groupe et toutes ses tâches",
    "msg_n_v": "Non valide",
    "e_b_e": "Base dans un formulaire existant",
    "e_s_r": "Ranger résultat dans table partagée",
    "t_complete": "Afficher Tâches Completées",
    "t_show": "Afficher Tâches pour:",
    "t_assign": "Assigner Utilisateur",
    "t_add_group": "ajouter Tâches Groupe",
    "t_lt_file": "Load Tasks From File",
    "t_choose_user": "Choose the user to assign to the selected tasks",
    "t_ce": "Clear Existing Tasks",
    "t_ce_warn": "This will clear all the existing data in the survey. Are you sure you want to do this?",
    "t_ceg": "Create Empty Task Group",
    "t_ep": "Existing Project",
    "t_es": "Existing Survey",
    "t_ns": "New Survey",
    "t_ft": "Filter Tasks",
    "t_fq": "Filter by Question",
    "t_so": "Selected Option",
    "t_sn": "Set Numeric Value",
    "t_st": "Set Text Value",
    "t_ue": "Update Existing Results",
    "t_ap": "Address Parameters",
    "t_nfc": "NFC or Location",
    "t_assigned": "Assigned",
    "t_fl": "File Loaded",
    "t_efnl": "Error file not loaded",
    "t_add_tasks": "Click on the map where you want to add new tasks. When finished click on 'Save Tasks' button",
    "t_add_tasks2": "Add Tasks",
    "t_save_tasks": "Save Tasks",
    "e_u_err": "Erreur Téléchargement Formulaire",
    "e_u_exists": "existes dans le projet",
    "e_h_rename": "Changer le nom du formulaire ou supprimer l'ancien formulaire",
    "e_u_sm_no_list": "select_multiple question sans list name",
    "e_h_sm_no_list": "Vérifier la feuille d'enquête. S'assurer que vous avez spécifié le list name pour tous les select_multiple questions",
    "e_u_so_no_list": "select_one question sans list name ",
    "e_h_so_no_list": "Vérifier la feuille de l'enquête. S'assurer que vous avez spécifié le list name pour tous les select_one questions",
    "e_unknown": "Erreur inconnue",
    "e_get_help": "Contacter le help desk",
    "e_calc": "Erreur de Calcul",
    "e_h_calc1": "Vérifier la colonne de 'calcul' pour une invalide formule (le résultat de la formule est soit vrais ou faux)",
    "e_h_calc2": "Autrement vérifier la colonne 'relevant' pour les formules qui donne pas vrais ou faux comme resultat",
    "e_inv_f": "Invalide Fonction",
    "e_h_f1": "Vérifier les lettres majuscules, toutes les lettres doivent être en minuscule",
    "e_h_f2": "Vérifier les erreurs d'épellation dans le nom de la fonction ",
    "e_val": "Erreur de validation",
    "e_circ": "Vérifier les références circulaires",
    "e_in_q": "dans la question",
    "e_h_c1": "La déclaration 'relevant' pour la question se réfère potentiellement à lui même plutôt à une autre question",
    "e_h_c2": "Les déclarations relevant sont évalués avant que la question est pausé donc elles ne peuvent pas se référer à leur propre questions ",
    "e_brackets": "Oublie de brackets dans la fonction",
    "e_text": "Erreur avec le texte suivant : ",
    "r_o_n": "Organisation Name",
    "r_y_n": "Your Name",
    "r_y_e": "Your Email",
    "r_y_o": "Organisation Website",
    "r_f": "Registration Form",
    "mon_l200": "(last 200)",
    "mon_gtb": "Group Totals by",
    "mon_nl": "Not Loaded",
    "mon_dup": "Duplicates",
    "mon_att": "Extra Attachments",
    "mon_sa": "Show As",
    "mon_zoom_grid": "Zoom to Grids",
    "mon_show_grid": "Show Grids",
    "mon_clear_grid": "Clear Grids",
    "mon_create_grid": "Create Grid",
    "mon_del_grid": "Delete Grids",
    "mon_sel_layer": "Select a layer to add to the map as an overlay",
    "mon_c_reg": "Create a new region",
    "mon_c_reg_i": "Enter a name for the region and the width of each cell in meters. Click on the map to set the centre of one of the cells. Press the \"shift\"button and drag the mouse to set the bounds.",
    "mon_name_cond": "(lowercase, no spaces or numbers)",
    "mon_cw": "Cell Width (in Meters. greater than 10)",
    "mon_centre": "Centre: (click on map)",
    "mon_bounds": "Boundary: (click and drag on map while pressing shift key)",
    "mon_sel_del": "Select the regions that you want to delete",
    "mon_ud": "Upload Date",
    "mon_pi": "Phone Identifier",
    "mon_fr": "Failure Reason",
    "mon_file": "File with raw results",
    "an_auth": "Author",
    "an_published": "Published",
    "an_dr": "Date Range",
    "an_csel": "Clear Selection",
    "Upload Time": "Charger",
    "_start": "Start Time",
    "_end": "End Time"
});