define(
{
    "m_home": "Accueil",
    "m_admin": "Administrer",
    "m_tm": "Gestion de Formulaire",
    "m_analysis": "Analyser",
    "m_reports": "Rapports",
    "m_refresh": "Actualiser",
    "m_export": "Exporter",
    "m_discuss": "Discuter",
    "m_modify": "Modifier",
    "m_web_forms": "Formulaires Web",
    "m_docs": "Documentation",
    "m_monitor": "Surveillance",
    "m_user": "Utilisateurs",
    "m_assign": "Taches",
    "m_help": "Aide",
    "m_forgot_password": "Mot de Passe Oublié",
    "ss_welcome": "Bienvenu dans Smap Server Version:",
    "ss_welcome2": "La description des changements inclus dans cette version peut être trouvé ici:",
    "ss_ft": "Obtenir Field Task",
    "ss_su": "Obtenir Smap Uploader",
    "c_project": "Sélectionné un Projet",
    "c_forms": "Formulaires",
    "c_forward": "Transférer",
    "c_name": "Nom",
    "c_file": "Fichier",
    "c_host": "Hôte",
    "c_user": "Utilisateur",
    "c_email": "Email",
    "c_lang": "Langage",
    "c_password": "Mot de Passe",
    "c_c_p": "Confirmer Mot de Passe",
    "c_r_p": "Réinitialiser Mot de Passe",
    "c_en": "Activer",
    "c_loc_f": "Formulaire Local:",
    "c_rem_f": "Formulaire Distant:",
    "c_rem_u": "Utilisateur Distant",
    "c_enabled": "Activé",
    "c_edit": "Editer",
    "c_del": "Supprimer",
    "c_download": "Télécharger",
    "c_done": "Terminer",
    "c_cancel": "Annuler ",
    "c_save": "Sauvegarder ",
    "c_block": "Bloquer",
    "ft_xls": "Formulaire XLS",
    "ft_xml": "Formulaire XML",
    "ft_pdf": "Formulaire PDF",
    "tm_s_del": "Afficher les Formulaires Supprimer ",
    "tm_d_forms": "Supprimer Formulaires",
    "tm_r_forms": "Restaurer Formulaires",
    "tm_e_forms": "Effacer Formulaires",
    "tm_c_form": "Créer un Formulaire",
    "tm_g_temp": "Télécharger Template ",
    "tm_g_temp_i1": "Téléchargez un modèle pour créer un nouveau formulaire sur votre ordinateur personnel. Lorsque vous avez terminé, le télécharger sur le serveur en cliquant sur ​​le bouton de Charger ci-dessous. Vous devrez tout d'abord sélectionner le fichier XLS contenant le formulaire que vous avez créé et lui donner un nom",
    "tm_g_temp_i3": "Guide de Référence ",
    "tm_g_temp_i4": "Autres éditeurs peuvent être utilisés, y compris:",
    "tm_ul_f": "Charger Formulaire",
    "tm_si": "Spécifiez identifiant de l'enquête",
    "tm_up": "Charger",
    "tm_add_for": "Ajouter Transfert",
    "tm_ref_f": "Actualiser Liste de Formulaires",
    "msg_wait": "Attente de la réponse du serveur. Réessayez dans quelques secondes",
    "msg_sel_survey": "Vous devez sélectionner une enquête",
    "msg_sel_q": "Vous devez sélectionner une question à afficher sur un graph",
    "msg_val_prot": "Protocol (http:// or https:// doit être spécifié avec le nom d'hôte",
    "msg_val_p": "Un Projet doit être sélectionné pour ce formulaire",
    "msg_val_rf": "Vous devez sélectionner un formulaire distant",
    "msg_val_rh": "Vous devez sélectionner un hôte distant",
    "msg_val_u_id": "Vous devez spécifier un ID utilisateur",
    "msg_val_pass": "Vous devez spécifier un mot de passe",
    "msg_val_let": "Nom doit commencer par une lettre ou underscore",
    "msg_add_forward": "Ajouter Transfert",
    "msg_edit_forward": "Editer Transfert",
    "msg_sel_form": "Sélectionner Formulaire:",
    "msg_err_save": "Erreur: Sauvegarde Echouée:",
    "msg_err_del": "Erreur: Suppression Echouée:",
    "msg_err_res": "Erreur: Restauration Echouée:",
    "msg_err_block": "Erreur: Blocage Echoué: ",
    "msg_err_get_f": "Erreur: Obtenir Formulaires Echoué:",
    "msg_err_cert": "Le serveur distant ne dispose pas d'un certificat signé, essayez d'utiliser http: // au lieu de https: //"
});