define(
{
    "m_home": "Accueil",
    "m_admin": "Administrer",
    "m_tm": "Gestion de Formulaire",
    "m_analysis": "Analyser",
    "m_reports": "Rapports",
    "m_refresh": "Actualiser",
    "m_export": "Exporter",
    "m_discuss": "Discuter",
    "m_modify": "Modifier",
    "m_web_forms": "Formulaires Web",
    "m_docs": "Documentation",
    "m_monitor": "Surveillance",
    "m_user": "Utilisateurs",
    "m_assign": "Taches",
    "m_help": "Aide",
    "m_forgot_password": "Mot de Passe Oublié",
    "m_locations": "Locations",
    "m_section": "Section",
    "m_notify": "Notifications",
    "ss_welcome": "Bienvenu dans Smap Server Version:",
    "ss_welcome2": "La description des changements inclus dans cette version peut être trouvé ici:",
    "ss_ft": "Obtenir Field Task",
    "ss_su": "Obtenir Smap Uploader",
    "c_project": "Sélectionné un Projet",
    "c_forms": "Formulaires",
    "c_forward": "Transférer",
    "c_name": "Nom",
    "c_type": "Type",
    "c_file": "Fichier",
    "c_host": "Hôte",
    "c_user": "Utilisateur",
    "c_email": "Email",
    "c_lang": "Langage",
    "c_password": "Mot de Passe",
    "c_c_p": "Confirmer Mot de Passe",
    "c_r_p": "Réinitialiser Mot de Passe",
    "c_en": "Activer",
    "c_loc_f": "Formulaire Local:",
    "c_rem_f": "Formulaire Distant:",
    "c_rem_u": "Utilisateur Distant",
    "c_enabled": "Activé",
    "c_edit": "Editer",
    "c_del": "Supprimer",
    "c_download": "Télécharger",
    "c_done": "Terminer",
    "c_cancel": "Annuler ",
    "c_save": "Sauvegarder ",
    "c_block": "Bloquer",
    "c_graph": "Graphique",
    "c_map": "Carte",
    "c_table": "Tableau",
    "c_tables": "Tableaux",
    "c_images": "Images",
    "c_title": "Titre",
    "c_comment": "Commentaire",
    "c_country": "Pays",
    "c_region": "Région",
    "c_district": "District",
    "c_community": "Communauté",
    "c_node": "Noeud",
    "c_relation": "Relation",
    "c_from": "A partir de",
    "c_to": "Vers",
    "c_properties": "Propriétés ",
    "c_question": "Question",
    "c_include": "Inclure",
    "c_unique": "Unique",
    "c_survey": "Enquête",
    "c_date": "Date",
    "c_none": "Aucun",
    "c_hour": "Heure",
    "c_day": "Jour",
    "c_week": "Semaine",
    "c_year": "Année",
    "c_matches": "Correspondances",
    "c_filter": "Filtre",
    "c_inclusive": "Inclusive",
    "c_value": "Valeur",
    "c_clear": "Effacer",
    "c_options": "Options",
    "c_data": "Donnée",
    "c_layers": "Couches",
    "c_settings": "Paramettres",
    "c_start": "Commencer",
    "c_back": "Arriere",
    "c_target": "Cible",
    "ft_xls": "Formulaire XLS",
    "ft_xml": "Formulaire XML",
    "ft_pdf": "Formulaire PDF",
    "tm_s_del": "Afficher les Formulaires Supprimer ",
    "tm_d_forms": "Supprimer Formulaires",
    "tm_r_forms": "Restaurer Formulaires",
    "tm_e_forms": "Effacer Formulaires",
    "tm_c_form": "Créer un Formulaire",
    "tm_g_temp": "Télécharger Template ",
    "tm_g_temp_i1": "Téléchargez un modèle pour créer un nouveau formulaire sur votre ordinateur personnel. Lorsque vous avez terminé, le télécharger sur le serveur en cliquant sur ​​le bouton de Charger ci-dessous. Vous devrez tout d'abord sélectionner le fichier XLS contenant le formulaire que vous avez créé et lui donner un nom",
    "tm_g_temp_i3": "Guide de Référence ",
    "tm_g_temp_i4": "Autres éditeurs peuvent être utilisés, y compris:",
    "tm_ul_f": "Charger Formulaire",
    "tm_si": "Spécifiez identifiant de l'enquête",
    "tm_up": "Charger",
    "tm_add_for": "Ajouter Transfert",
    "tm_ref_f": "Actualiser Liste de Formulaires",
    "a_exp_title": "Exporter Resultats",
    "a_exp_leg1": "Sélectionner Formulaire",
    "a_exp_leg2": "Format de Sortie",
    "a_exp_notes": "Exporter Notes",
    "a_exp_split": "Découper Lat/Long:",
    "a_sel_ways": "Sélectionner Chemin (Si dispo) ",
    "a_sel_forms": "Sélectionner formulaire à inclure",
    "a_sel_model": "Editer modèle d'enquête ",
    "a_type": "Type de Graph",
    "a_showon": "Afficher dans",
    "a_ss": "Sélectionner enquête",
    "a_sq": "Sélectionner Question",
    "a_gb": "Grouper par ",
    "a_ts": "Séries de temps",
    "a_g_gps": "Les coordonnées GPS à l'intérieur de la région",
    "a_fbv": "Filtre par valeur",
    "a_from_date": "A partir de la date",
    "a_to_date": "A la date",
    "a_fq": "Filtrer question",
    "msg_wait": "Attente de la réponse du serveur. Réessayez dans quelques secondes",
    "msg_sel_survey": "Vous devez sélectionner une enquête",
    "msg_sel_q": "Vous devez sélectionner une question à afficher sur un graph",
    "msg_val_prot": "Protocol (http:// ou https://) doit être spécifié avec le nom d'hôte",
    "msg_val_p": "Un Projet doit être sélectionné pour ce formulaire",
    "msg_val_rf": "Vous devez sélectionner un formulaire distant",
    "msg_val_rh": "Vous devez sélectionner un hôte distant",
    "msg_val_u_id": "Vous devez spécifier un ID utilisateur",
    "msg_val_pass": "Vous devez spécifier un mot de passe",
    "msg_val_let": "Nom doit commencer par une lettre ou underscore",
    "msg_add_forward": "Ajouter Transfert",
    "msg_edit_forward": "Editer Transfert",
    "msg_sel_form": "Sélectionner Formulaire:",
    "msg_err_save": "Erreur: Sauvegarde Echouée:",
    "msg_err_del": "Erreur: Suppression Echouée:",
    "msg_err_res": "Erreur: Restauration Echouée:",
    "msg_err_block": "Erreur: Blocage Echoué: ",
    "msg_err_get_f": "Erreur: Obtenir Formulaires Echoué:",
    "msg_err_cert": "Le serveur distant ne dispose pas d'un certificat signé, essayez d'utiliser http: // au lieu de https: //",
    "e_u_err": "Erreur Téléchargement Formulaire",
    "e_u_exists": "existes dans le projet",
    "e_h_rename": "Changer le nom du formulaire ou supprimer l'ancien formulaire",
    "e_u_sm_no_list": "select_multiple question sans list name",
    "e_h_sm_no_list": "Vérifier la feuille d'enquête. S'assurer que vous avez spécifié le list name pour tous les select_multiple questions",
    "e_u_so_no_list": "select_one question sans list name ",
    "e_h_so_no_list": "Vérifier la feuille de l'enquête. S'assurer que vous avez spécifié le list name pour tous les select_one questions",
    "e_unknown": "Erreur inconnue",
    "e_get_help": "Contacter le help desk",
    "e_calc": "Erreur de Calcul",
    "e_h_calc1": "Vérifier la colonne de 'calcul' pour une invalide formule (le résultat de la formule est soit vrais ou faux)",
    "e_h_calc2": "Autrement vérifier la colonne 'relevant' pour les formules qui donne pas vrais ou faux comme resultat",
    "e_inv_f": "Invalide Fonction",
    "e_h_f1": "Vérifier les lettres majuscules, toutes les lettres doivent être en minuscule",
    "e_h_f2": "Vérifier les erreurs d'épellation dans le nom de la fonction ",
    "e_val": "Erreur de validation",
    "e_circ": "Vérifier les références circulaires",
    "e_in_q": "dans la question",
    "e_h_c1": "La déclaration 'relevant' pour la question se réfère potentiellement à lui même plutôt à une autre question",
    "e_h_c2": "Les déclarations relevant sont évalués avant que la question est pausé donc elles ne peuvent pas se référer à leur propre questions ",
    "e_brackets": "Oublie de brackets dans la fonction",
    "e_text": "Erreur avec le texte suivant : "
});