define(
{
    "m_home": "Inicio",
    "m_admin": "Administración",
    "m_tm": "Gestion de formularios",
    "m_analysis": "Analisis",
    "m_reports": "Reportes",
    "m_refresh": "Actualizar",
    "m_export": "Exportar",
    "m_discuss": "Discusión",
    "m_modify": "Modificar",
    "m_web_forms": "Formularios Web",
    "m_docs": "Documentacion",
    "m_monitor": "Seguimiento",
    "m_user": "Usuarios",
    "m_assign": "Tareas",
    "m_help": "Ayuda",
    "m_forgot_password": "Contrasena olvidada",
    "m_locations": "Localizaciones",
    "m_section": "Seccion",
    "m_notify": "Notificaciones",
    "ss_welcome": "Bienvenido al Servidor Smap Version: ",
    "ss_welcome2": "Una descripcion de los cambios en esta version puede encontrarse aqui:",
    "ss_ft": "Obtener Field Task",
    "ss_su": "Obtener el Cargador Smap",
    "c_project": "Seleccionar Proyecto",
    "c_forms": "Formularios",
    "c_forward": "Avanzar",
    "c_name": "Nombre",
    "c_type": "Tipo",
    "c_file": "Archivo",
    "c_host": "Host",
    "c_user": "Usuario",
    "c_email": "Email",
    "c_lang": "idioma",
    "c_password": "Contrasena",
    "c_c_p": "Confirmar Contrasena",
    "c_r_p": "Cambiar Contrasena",
    "c_en": "Activar",
    "c_loc_f": "Formulario local:",
    "c_rem_f": "Formulario Remoto",
    "c_rem_u": "Usuario Remoto",
    "c_enabled": "Activado",
    "c_edit": "Editar",
    "c_del": "Suprimir",
    "c_download": "Descargar",
    "c_done": "Hecho",
    "c_cancel": "Cancelar",
    "c_save": "Guardar",
    "c_block": "Bloquear",
    "c_graph": "Grafico",
    "c_map": "Mapa",
    "c_table": "Tabla",
    "c_tables": "Tablas",
    "c_images": "Imagenes",
    "c_title": "Titulo",
    "c_comment": "Comentario",
    "c_country": "Pais",
    "c_region": "Provincia",
    "c_district": "Districto",
    "c_community": "Comunidad",
    "c_node": "Nodo",
    "c_relation": "Relacion",
    "c_from": "De",
    "c_to": "A",
    "c_properties": "Propriedades",
    "c_question": "Pregunta",
    "c_include": "Incluir",
    "c_unique": "Unico",
    "c_survey": "Encuesta",
    "c_date": "Fecha",
    "c_none": "Ninguno",
    "c_hour": "Hora",
    "c_day": "Dia",
    "c_week": "Semana",
    "c_year": "Anno",
    "c_matches": "Corespondencias",
    "c_filter": "Filtrar",
    "c_inclusive": "Inclusive",
    "c_value": "Valor",
    "c_clear": "Limpiar",
    "c_options": "Opciones",
    "c_data": "Datos",
    "c_layers": "Capas",
    "c_settings": "Ajustes",
    "c_start": "Empezar",
    "c_back": "Atras",
    "c_target": "Objetivo",
    "ft_xls": "Fomulario XLS",
    "ft_xml": "Formulario XLM",
    "ft_pdf": "Formulario PDF",
    "tm_s_del": "Mostrar formularios eliminados",
    "tm_d_forms": "Eliminar Formularios",
    "tm_r_forms": "Recuperar Formularios",
    "tm_e_forms": "Borrar Formularios",
    "tm_c_form": "Crear Formulario",
    "tm_g_temp": "Descargar Plantilla",
    "tm_g_temp_i1": "Descarga una plantilla para crear un nuevo formulario en su computador personal. Cuando haya terminado, podrá subirlo al servidor haciendo click en el boton de abajo. Usted primero necesita seleccionar el archivo XLS que contiene el formulario y darle un nombre",
    "tm_g_temp_i3": "Guia de Referencia",
    "tm_g_temp_i4": "Otros editores que puede usar son:",
    "tm_ul_f": "Subir un Formulario",
    "tm_si": "Especifique el identificador de la encuesta",
    "tm_up": "Cargar",
    "tm_add_for": "Agregar adelante",
    "tm_ref_f": "Actualizar Lista de Formularios",
    "a_exp_title": "Exportar Resultados",
    "a_exp_leg1": "Seleccionar un Formulario",
    "a_exp_leg2": "Formato de Salida",
    "a_exp_notes": "Notas de Exportacion",
    "a_exp_split": "Dividir Lat / Lon",
    "a_sel_ways": "Seleccione modos(si tiene)",
    "a_sel_forms": "Seleccione formularios a incluir:",
    "a_sel_model": "Editar Modelo de Encuesta",
    "a_type": "Tipo de Grafica",
    "a_showon": "Se muestra en",
    "a_ss": "Seleccione encuesta",
    "a_sq": "Seleccione pregunta",
    "a_gb": "Agrupe por",
    "a_ts": "Series de Tiempo",
    "a_g_gps": "Coordenadas GPS dentro de una region",
    "a_fbv": "Filtrar por valor",
    "a_from_date": "Desde fecha",
    "a_to_date": "Hasta Fecha",
    "a_fq": "Filtar pregunta",
    "msg_wait": "Esperando respuesta del servidor. Por favor intente de nuevo en unos segurndos",
    "msg_sel_survey": "Se debe seleccionar uan encuesta",
    "msg_sel_q": "Se debe seleccionar una pregunta para mostrar en la grafica",
    "msg_val_prot": "Se debe especificar un protocolo (http:// or https://) con el hostname",
    "msg_val_p": "Se debe seleccionar un proyecto para este formulario",
    "msg_val_rf": "Se debe seleccionar un formulario remoto",
    "msg_val_rh": "Debe seleccionar un hosting remoto",
    "msg_val_u_id": "Debe especificar un Id de usuario",
    "msg_val_pass": "Debe especificar una contraseña",
    "msg_val_let": "El nombre debe empezar con una letra o guion al piso",
    "msg_add_forward": "Agregue hacia adelante",
    "msg_edit_forward": "Edite hacia adelante",
    "msg_sel_form": "Seleccione formulario:",
    "msg_err_save": "Error: No se  pudo guardar:",
    "msg_err_del": "Error:  No se pudo eliminar:",
    "msg_err_res": "Error: No se pudo restaurar:",
    "msg_err_block": "Error: No se pudo bloquear:",
    "msg_err_get_f": "Error: Fallo en carga de formularios:",
    "msg_err_cert": "El servidor remoto no tiene una firma digital válida. Intente usar http:// en vez de https://",
    "e_u_err": "Error en cargue de formulario",
    "e_u_exists": "existe en proyecto",
    "e_h_rename": "Cambie el nombre del formulario o elimine el formulario anterior",
    "e_u_sm_no_list": "pregunta tipo selección múltiple (select_multiple) sin lista de nombres",
    "e_h_sm_no_list": "Revise el archivo .xls de la encueta. Asegúrese de haber especificado una lista de nombres para todas las preguntas de selección múltiple (select_multiple)\n",
    "e_u_so_no_list": "pregunta tipo selección única (select_multiple) sin lista de nombres",
    "e_h_so_no_list": "Revise el archivo .xls de la encuesta. Asegúrese de haber especificado una lista de nombres para todas las preguntas de selección única (select_one)",
    "e_unknown": "Error desconocido",
    "e_get_help": "Contacte la mesa de ayuda",
    "e_calc": "Error en cálculo",
    "e_h_calc1": "Revise la columna 'calculation' si hay una formual inválida (Una formula válida da como resultado verdadero (true) o falso (false))",
    "e_h_calc2": "Si no revise la columna 'relevant' si alguna formula no da como resultado true o false ",
    "e_inv_f": "Función inválida",
    "e_h_f1": "Revise si hay letras mayúsculas. Todas las letras deben estra en minúsculas",
    "e_h_f2": "Revise errores de escritura en el nombre de la función",
    "e_val": "Error de Validacion",
    "e_circ": "Revise por referencias circulares",
    "e_in_q": "en pregunta",
    "e_h_c1": "Una declaración 'relevant´en una pregunta se está refiriendo a ella misma en vez de a otra pregunta. \n",
    "e_h_c2": "Declaraciones relevantes se están evaluando antes de una pregunta que si es ejecutada no podrá referirse a sus propias prepuntas.",
    "e_brackets": "Corchetes no coincidentes en funcion",
    "e_text": "Error en el siguiente texto:"
});