define(
{
    "m_home": "Inicio",
    "m_admin": "Administración",
    "m_tm": "Formularios",
    "m_analysis": "Análisis",
    "m_reports": "Reportes",
    "m_refresh": "Actualizar",
    "m_export": "Exportar",
    "m_discuss": "Discusión",
    "m_modify": "Modificar",
    "m_web_forms": "Form. Web",
    "m_docs": "Documentación",
    "m_monitor": "Monitoreo de Datos",
    "m_user": "Usuarios",
    "m_assign": "Tareas",
    "m_help": "Ayuda",
    "m_forgot_password": "Recuperar Contraseña ",
    "m_register": "Registrarse",
    "m_locations": "Rastreo",
    "m_section": "Sección",
    "m_notify": "Notificaciones",
    "m_view": "Ver",
    "m_attach": "Cargar adjuntos",
    "m_modules": "Modulos",
    "m_open": "Abrir",
    "m_new": "Nuevo",
    "m_import": "Importar",
    "m_calculations": "Cálculos",
    "m_resources": "Recursos Compartidos",
    "m_review": "Revisión",
    "m_mf": "Formularios con Seguimiento",
    "m_manage": "Seguimiento",
    "m_manage_dash": "Tablero de Gestión",
    "m_s_m_f": "Configurar Formularios con Seguimiento",
    "m_task_m": "Gestión de Tareas",
    "m_user_profile": "Perfil de Usuario",
    "m_login": "Ingresar",
    "ss_welcome": "Bienvenido al Servidor Versión: ",
    "ss_welcome2": "Cambios en la versión",
    "ss_ft": "Obtener App móvil",
    "ss_su": "Obtener el Cargador Smap",
    "c_apply": "Aplicar",
    "c_desc": "Descripción",
    "c_project": "Seleccionar Proyecto",
    "c_forms": "Formularios Activos",
    "c_form": "Formulario",
    "c_forward": "Enviar",
    "c_forwarded": "Reenviados a otro servidor",
    "c_name": "Nombre",
    "c_company_name": "Empresa",
    "c_type": "Tipo",
    "c_file": "Archivo",
    "c_host": "Servidor",
    "c_user": "Usuario",
    "c_email": "Email",
    "c_lang": "Idioma",
    "c_langs": "Idiomas",
    "c_orientation": "Orientación",
    "c_password": "Contraseña",
    "c_c_p": "Confirmar Contraseña",
    "c_r_p": "Cambiar Contraseña",
    "c_en": "Activar",
    "c_loc_f": "Formulario Local:",
    "c_rem_f": "Formulario Remoto",
    "c_rem_u": "Usuario Remoto",
    "c_enabled": "Activado",
    "c_edit": "Editar",
    "c_del": "Suprimir",
    "c_download": "Descargar",
    "c_done": "Realizado",
    "c_cancel": "Cancelar",
    "c_save": "Guardar",
    "c_submit": "Enviar",
    "c_submitted": "Datos Enviados",
    "c_test": "Verificar",
    "c_validate": "Validar",
    "c_close": "Cerrar",
    "c_logout": "Cerrar Sesión",
    "c_block": "Inactivar",
    "c_graph": "Gráfica",
    "c_map": "Mapa",
    "c_map_layers": "Cambiar Mapa",
    "c_table": "Tabla",
    "c_tables": "Tablas",
    "c_images": "Imágenes",
    "c_title": "Titulo",
    "c_comment": "Comentario",
    "c_country": "País",
    "c_region": "Región",
    "c_district": "Departamento",
    "c_community": "Ciudad",
    "c_node": "Nodo",
    "c_relation": "Relación",
    "c_from": "De",
    "c_subject": "Asunto",
    "c_to": "A",
    "c_properties": "Propiedades",
    "c_question": "Pregunta",
    "c_include": "Incluir",
    "c_unique": "Unico",
    "c_survey": "Formulario",
    "c_date": "Fecha",
    "c_none": "Ninguno",
    "c_hour": "Hora",
    "c_day": "Día",
    "c_week": "Semana",
    "c_month": "Mes",
    "c_year": "Año",
    "c_matches": "Correspondencias",
    "c_filter": "Filtrar",
    "c_inclusive": "Inclusive",
    "c_value": "Valor",
    "c_clear": "Limpiar",
    "c_options": "Opciones",
    "c_data": "Datos",
    "c_layers": "Capas",
    "c_settings": "Ajustes",
    "c_start": "Empezar",
    "c_back": "Atras",
    "c_target": "Objetivo",
    "c_content": "Contenido",
    "c_attach": "Adjunto",
    "c_details": "Detalles",
    "c_action": "Acción",
    "c_mapid": "Id. del Mapa",
    "c_zoom": "Niveles de Zoom",
    "c_zoom_data": "Zoom a Datos",
    "c_vector_data": "Datos del Vector",
    "c_vector_style": "Estilo del Vector",
    "c_portrait": "Vertical",
    "c_landscape": "Horizontal",
    "c_tools": "Herramientas",
    "c_required": "Establecer como Requerida",
    "c_not_required": "Establecer como Opcional",
    "c_del_sel": "Eliminar Seleccionada",
    "c_print": "Imprimir",
    "c_repeat": "Repetir",
    "c_scheduled": "Programada",
    "c_t_c": "Términos y condiciones",
    "c_agree": "Estoy de acuerdo con",
    "c_select": "Seleccionar",
    "c_status": "Estatus",
    "c_coords": "Coordenadas",
    "c_task": "Tarea",
    "c_rec": "(Recomendado)",
    "c_source": "Fuente",
    "c_show": "Mostrar",
    "c_hide": "Ocultar",
    "c_totals": "Totales",
    "c_instances": "Instancias",
    "c_device": "Dispositivo",
    "c_success": "Exitosos",
    "c_errors": "Errores",
    "c_error": "Error",
    "c_lt": "Hora Local",
    "c_location": "Ubicación",
    "c_ident": "ID",
    "c_version": "Versión",
    "c_deleted": "Eliminado",
    "c_yes": "Si",
    "c_no": "No",
    "c_reason": "Razón",
    "c_complete": "Completo",
    "c_record": "Registro",
    "c_records": "Registros",
    "c_of": "de",
    "c_media": "Multimedia",
    "c_changes": "Cambios",
    "c_calc": "Cálculos",
    "c_trans": "Traducir",
    "ft": "Tipo de Archivo",
    "ft_xls": "Formulario XLS",
    "ft_xls_orig": "Archivo XLS Original ",
    "ft_xml": "Formulario XLM",
    "ft_codebook": "Especificaciones del Formulario",
    "ft_pdf": "Plantilla PDF",
    "tm_s_del": "Mostrar formularios eliminados",
    "tm_d_forms": "Eliminar Formularios",
    "tm_r_forms": "Recuperar Formularios",
    "tm_e_forms": "Borrar Formularios",
    "tm_c_form": "Crear Un Formulario",
    "tm_c_xls": "Usar Excel  u otro Editor de Hojas de Cálculo",
    "tm_g_temp": "Descargar Plantilla",
    "tm_g_new": "Crear Nuevo Formulario",
    "tm_g_temp_i1": "Descarga una plantilla para crear un nuevo formulario. Cuando haya terminado, podrá subirlo al servidor haciendo click en el botón de abajo, seleccionando el archivo XLS que contiene el formulario y asignarle el nombre correspondiente",
    "tm_g_temp_i3": "Guía de Referencia",
    "tm_ul_f": "Subir Archivo de Excel",
    "tm_si": "Especifique el Identificador del formulario",
    "tm_up": "Subir Plantilla",
    "tm_add_for": "Agregar Adelante",
    "tm_ref_f": "Actualizar Lista de Formularios",
    "a_exp_title": "Exportar Resultados",
    "a_exp_leg1": "Seleccione formulario",
    "a_exp_leg2": "Formato de Salida:",
    "a_exp_notes": "Exportar Notas:",
    "a_exp_split": "Separar Coordenadas:",
    "a_exp_merge": "Comprimir múltiples selecciones:",
    "a_sel_ways": "Seleccione modos (si tiene):",
    "a_sel_forms": "Seleccione las tablas a incluir:",
    "a_sel_model": "Editar Modelo de Formulario",
    "a_type": "Tipo de Grafica",
    "a_showon": "Mostrar sobre",
    "a_ss": "Seleccione formulario",
    "a_sq": "Seleccione pregunta",
    "a_gb": "Agrupar por",
    "a_ts": "Series de Tiempo",
    "a_g_gps": "Coordenadas GPS dentro de región",
    "a_fbv": "Filtrar por valor",
    "a_from_date": "Desde fecha",
    "a_to_date": "Hasta Fecha",
    "a_fq": "Filtrar pregunta",
    "a_res": "Por favor suministre una razón",
    "a_mb": "Marcado Erróneo",
    "a_cm": "Miembros de Cluster",
    "a_dv": "Mostrar Detalles",
    "msg_wait": "Esperando respuesta del servidor. Por favor intente de nuevo en unos segurndos",
    "msg_reason": "Por favor suministre una razón:",
    "msg_sel_survey": "Se debe seleccionar un formulario",
    "msg_sel_q": "Se debe seleccionar una pregunta para mostrar en la grafica",
    "msg_val_prot": "Se debe especificar un protocolo (http:// or https://) con el nombre del servidor",
    "msg_val_p": "Se debe seleccionar un proyecto para este formulario",
    "msg_val_rf": "Se debe seleccionar un formulario remoto",
    "msg_val_rh": "Debe seleccionar un servidor remoto",
    "msg_val_u_id": "Debe especificar un Id de usuario",
    "msg_val_pass": "Debe especificar una contraseña",
    "msg_val_let": "El nombre debe empezar con una letra o guion al piso",
    "msg_add_notification": "Agregar Notificación",
    "msg_edit_notification": "Editar Notificación",
    "msg_add_map": "Agregar Mapa",
    "msg_edit_map": "Editar Mapa",
    "msg_sel_form": "Seleccione formulario:",
    "msg_sel_media": "Seleccionar Pregunta Multimedia",
    "msg_err_save": "Error: NO se pudo Guardar:",
    "msg_err_del": "Error:  NO se pudo Eliminar:",
    "msg_err_upd": "Error en cargue:",
    "msg_err_res": "Error: NO se pudo Restaurar:",
    "msg_err_block": "Error: NO se pudo Inhabilitar:",
    "msg_err_get_f": "Error: Fallo en carga de formularios:",
    "msg_err_wait": "Esperando conexión con servidor  o no hay formularios en este proyecto para asignar a un usuario. Si el proyecto tiene respuestas reintente en pocos segundos.",
    "msg_err_cert": "El servidor remoto no tiene una firma digital válida. Intente usar http:// en vez de https://",
    "msg_no_edit_rep": "No se puede editar un registro que ha sido reemplazado por otro registro",
    "msg_confirm_del": "Esta seguro que quiere borrar",
    "msg_confirm_tasks": "este grupo y todas sus tareas?",
    "msg_n_v": "Inválido",
    "msg_u_f": "Error de fallo en subida de archivo",
    "msg_u_nt": "No se encontraron tags NFC",
    "msg_csv": "Sólo archivos CSV y ZIP conteniendo archivos CSV o multimedia son permitidos",
    "msg_inv_email": "No es un e-mail válido",
    "e_b_e": "Crear desde un formulario existente",
    "e_s_r": "Almacenar resultados en tabla compartida  con datos origen",
    "t_complete": "Mostrar Tareas Completadas",
    "t_show": "Mostrar tareas por:",
    "t_assign": "Asignar a Usuario",
    "t_add_group": "Adicionar Grupo de Tareas",
    "t_del_group": "Borrar Grupo de Tareas",
    "t_lt_file": "Cargar Tareas desde Archivo",
    "t_choose_user": "Escoja el usuario para asignar la tarea seleccionada",
    "t_ce": "Borrar tareas existentes",
    "t_ce_warn": "Esto borrará todos los datos existentes del formulario. Seguro que quiere hacer esto?",
    "t_ceg": "Crear Grupo de Tareas Vacio",
    "t_cfe": "Crear desde datos existentes",
    "t_ep": "Proyecto Existente",
    "t_es": "Formulario Existente",
    "t_ns": "Nuevo Formulario",
    "t_ft": "Filtro de Tareas",
    "t_fq": "Filtrar por Pregunta",
    "t_so": "Opción Seleccionada",
    "t_sn": "Establecer Valor Numérico",
    "t_st": "Establecer Valor de Texto",
    "t_ue": "Actualizar Resultados Existentes",
    "t_ap": "Dirección de Parámetros",
    "t_nfc": "NFC o ubicación",
    "t_assigned": "Asignada a:",
    "t_fl": "Archivo cargado",
    "t_efnl": "Error archivo no cargado",
    "t_add_tasks": "Haga click en el mapa donde se quiera adicionar tareas. Cuando termine haga click en botón 'Guardar Tareas'",
    "t_add_task": "Agregar Tarea",
    "t_edit_task": "Editar Tarea",
    "t_add_tasks2": "Agregar Tareas",
    "t_save_tasks": "Guardar Tareas",
    "t_tasks_only": "No mostrar formularios en dispositivo móvil (Sólo tareas) ",
    "t_tg": "Grupo de Tareas",
    "t_tasks": "Tareas",
    "t_id": "Datos Iniciales",
    "t_n_s": "Tareas sin fecha de inicio",
    "t_drag": "Arrastre una tarea y agréguela al calendario",
    "e_u_err": "Error en subida de formulario",
    "e_u_exists": "existe en proyecto",
    "e_h_rename": "Cambie el nombre del formulario o elimine el formulario anterior",
    "e_u_sm_no_list": "pregunta tipo selección múltiple (select_multiple) sin lista de nombres",
    "e_h_sm_no_list": "Revise el archivo .xls del formulario. Asegúrese de haber especificado una lista de nombres para todas las preguntas de selección múltiple (select_multiple)\n",
    "e_u_so_no_list": "pregunta tipo selección única (select_multiple) sin lista de nombres",
    "e_h_so_no_list": "Revise el archivo .xls del formulario. Asegúrese de haber especificado una lista de nombres para todas las preguntas de selección única (select_one)",
    "e_unknown": "Error desconocido",
    "e_get_help": "Contacte la mesa de ayuda:  contacto@kontrolid.com",
    "e_calc": "Error en cálculo",
    "e_h_calc1": "Revise la columna 'calculation' si hay una formula inválida (Una formula válida da como resultado verdadero (true) o falso (false))",
    "e_h_calc2": "Si no revise la columna 'relevant' si alguna formula no da como resultado true o false ",
    "e_inv_f": "Función inválida",
    "e_h_f1": "Revise si hay letras mayúsculas. Todas las letras deben estar en minúsculas",
    "e_h_f2": "Revise errores de escritura en el nombre de la función",
    "e_val": "Error de Validación",
    "e_circ": "Revise por referencias circulares",
    "e_in_q": "en pregunta",
    "e_h_c1": "Una declaración 'relevant´en una pregunta se está refiriendo a ella misma en vez de a otra pregunta. \n",
    "e_h_c2": "Declaraciones relevantes se están evaluando antes de una pregunta que si es ejecutada no podrá referirse a sus propias preguntas.",
    "e_brackets": "Corchetes no coincidentes en función",
    "e_text": "Error en el siguiente texto:",
    "r_o_n": "Organización",
    "r_y_n": "Nombre",
    "r_y_e": "Email",
    "r_y_o": "Sitio web",
    "r_f": "Formulario de Registro",
    "mon_l200": "(últimas 200)",
    "mon_gtb": "Agrupar Totales por",
    "mon_nl": "No cargado",
    "mon_dup": "Duplicados",
    "mon_att": "Con Adjuntos Extra",
    "mon_sa": "Mostrar como",
    "mon_zoom_grid": "Zoom a Cuadrículas",
    "mon_show_grid": "Mostrar Cuadrículas",
    "mon_clear_grid": "Limpiar Cuadrículas",
    "mon_create_grid": "Crear Cuadrículas",
    "mon_del_grid": "Eliminar Cuadrículas",
    "mon_sel_layer": "Seleccionar un capa adicional para mostrar sobre mapa.",
    "mon_c_reg": "Crear una nueva región",
    "mon_c_reg_i": "Ingrese un nombre para la región y el ancho de las celdas en metros. Haga click en el mapa para fijar el centro de las celdas. Presione la tecla mayúsculas) y arrastre el ratón para fijar los límites.",
    "mon_name_cond": "(minúsculas, sin espacios o números)",
    "mon_cw": "Ancho de Celda (in Metros. mayor que 10)",
    "mon_centre": "Centrar: (Haga clic en mapa)",
    "mon_bounds": "Límites: (haga clic y arrastre en el mapa mientras presiona la tecla de mayúsculas",
    "mon_sel_del": "Seleccione las regiones que quiere eliminar",
    "mon_ud": "Fecha de Cargue",
    "mon_pi": "IMEI del Dispositivo",
    "mon_fr": "Causa del Fallo:",
    "mon_file": "Archivo de datos",
    "an_auth": "Autor",
    "an_published": "Publicado",
    "an_dr": "Rango de Fechas",
    "an_csel": "Limpiar Selección",
    "Upload Time": "Subir",
    "_start": "Hora Inicio",
    "_end": "Hora Final",
    "percent": "Porcentaje",
    "count": "Conteo",
    "none": "Ninguno",
    "average": "Promedio",
    "wf_sig": "Firma",
    "ed_qt": "Pregunta de Texto",
    "ed_ct": "Pregunta de Selección",
    "ed_qh": "Texto de Ayuda",
    "ed_ap": "Apariencia",
    "ed_con": "Restricción",
    "ed_r_msg": "Mensaje de Texto Requerido",
    "ed_o_o_g": "Sólo una pregunta de geolocalización puede ser usada en un formulario",
    "mf_fd": "Datos del Formulario",
    "mf_md": "Gestión de Datos",
    "mf_sc": "Columnas A Mostrar",
    "mf_sc_i": "Seleccione las columnas que quiera visualizar en la tabla y luego presione el botón 'Aplicar'. Las columnas se pueden ordenar posteriormente.",
    "lo_back": "Atras",
    "lo_out": "Se ha cerrado sesión del servidor",
    "lo_lo": "Sesión Finalizada"
});