define(
{
    "m_home": "الرئيسية",
    "m_admin": "مشرف",
    "m_tm": "النماذج",
    "m_analysis": "التحليل",
    "m_reports": "التقارير",
    "m_reports_def": "تقارير افتراضية ",
    "m_reports_org": "تقارير المنظمة ",
    "m_refresh": "تحديث",
    "m_export": "تصدير",
    "m_discuss": "مناقشة",
    "m_modify": "تعديل",
    "m_data_mod": "نماذج الويب",
    "m_web_forms": "نماذج الويب",
    "m_docs": "توثيق ",
    "m_monitor": "مراقبة ",
    "m_user": "المستخدمين",
    "m_assign": "المهام",
    "m_help": "المساعدة",
    "m_forgot_password": "نسيت كلمة المرور",
    "m_register": "التسجيل",
    "m_locations": "المناطق",
    "m_section": "الشعب",
    "m_notify": "أشعارات ",
    "m_view": "رأي ",
    "m_attach": "إرفاق ملفات التحميل",
    "m_modules": "وحدات",
    "m_open": "فتح ",
    "m_new": "جديد ",
    "m_import": "استيراد ",
    "m_calculations": "عمليات حسابية ",
    "m_resources": "موارد مشتركة ",
    "m_review": "إعادة النظر ",
    "m_mf": "أشكال التمكن ",
    "m_br": "تصفح نتائج البحث ",
    "m_manage": "إدارة ",
    "m_dash": "لوحة القيادة ",
    "m_s_m_f": "اعداد امكانية الأشكال ",
    "m_task_m": "إدارة المهام ",
    "m_user_profile": "ملف تعريف المستخدم ",
    "m_login": "تسجيل الدخول ",
    "m_logs": "السجلات ",
    "m_info": "معلومات ",
    "m_os": "مراقبة ",
    "ss_welcome": "مرحبا في اصدار الخادم smap",
    "ss_welcome2": "التغييرات في هذا الإصدار",
    "ss_ft": "الحصول على عمل ميداني ",
    "ss_su": "الحصول على  مُحملsmap ",
    "c_apply": "تطبيق ",
    "c_desc": "وصف",
    "c_project": "إختيار مشروع ",
    "c_forms": "النماذج",
    "c_form": "نموذج ",
    "c_forward": "إلى الأمام",
    "c_forwarded": "تقدم",
    "c_name": "الاسم",
    "c_company_name": "اسم الشركة",
    "c_company_addr": "عنوان الشركة ",
    "c_company_phone": "هاتف الشركة ",
    "c_company_email": "البريد الإلكتروني للشركة ",
    "c_type": "النوع",
    "c_file": "الملف",
    "c_host": "مضيف",
    "c_user": "المستخدم",
    "c_projects": "مشاريع",
    "c_email": "البريد الإلكتروني ",
    "c_twitter": "تويتر ",
    "c_lang": "اللغة",
    "c_langs": "اللغات",
    "c_orientation": "اتجاه ",
    "c_password": "كلمة المرور",
    "c_c_p": "تأكيد كلمة المرور",
    "c_r_p": "إعادة تعيين كلمة المرور",
    "c_en": "تفعيل",
    "c_loc_f": "نموذج محلي ",
    "c_rem_f": "نموذج عن بعد ",
    "c_rem_u": "مستخدم بعيد ",
    "c_enabled": "تمكين/تفعيل ",
    "c_edit": "تصحيح ",
    "c_del": "حذف ",
    "c_download": "تحميل",
    "c_upload": "تحميل ",
    "c_done": "تم",
    "c_cancel": "إلغاء ",
    "c_save": "حفظ",
    "c_saved": "تم الحفظ ",
    "c_submit": "عرض ",
    "c_submitted": "تم العرض ",
    "c_test": "اختبار ",
    "c_validate": "تحقق من صحة ",
    "c_close": "إغلاق ",
    "c_logout": "تسجيل الخروج ",
    "c_block": "حظر",
    "c_blocked": "تم الحظر ",
    "c_graph": "رسم بياني ",
    "c_map": "خريطة ",
    "c_maps": "خرائط ",
    "c_map_layers": "طبقات الخريطة ",
    "c_table": "جدول ",
    "c_tables": "جداول ",
    "c_images": "صورة ",
    "c_title": "عنوان/اللقب ",
    "c_comment": "تعليق",
    "c_country": "دولة ",
    "c_region": "منطقة/ولاية ",
    "c_district": "حي/ بلدة",
    "c_community": "تواصل اجتماعي ",
    "c_node": "نقطة اللقاء ",
    "c_relation": "علاقة ",
    "c_from": "من عند/ حسب",
    "c_subject": "موضوع ",
    "c_to": "إلى ",
    "c_properties": "خصائص ",
    "c_question": "سؤال ",
    "c_questions": "أسئلة ",
    "c_choices": "اختيارات ",
    "c_include": "تتضمن ",
    "c_unique": "فريد",
    "c_survey": "تفقد / دراسة",
    "c_date": "موعد / تاريخ",
    "c_dateq": "موعد السؤال ",
    "c_none": "لا شيء ",
    "c_period": "فترة  / مدة ",
    "c_hour": "ساعة",
    "c_day": "يوم",
    "c_week": "اسبوع ",
    "c_month": "شهر ",
    "c_year": "سنة ",
    "c_matches": "ثقاب",
    "c_filter": "منقي",
    "c_inclusive": "شامل",
    "c_value": "قيمة ",
    "c_clear": "توضيح / تنظيف ",
    "c_options": "خيارات ",
    "c_data": "البيانات ",
    "c_layers": "طبقات ",
    "c_settings": "إعدادات ",
    "c_start": "بداية ",
    "c_back": "رجوع / عودة ",
    "c_target": "إستهداف  / هدف",
    "c_content": "المحتوى",
    "c_attach": "ربط / وصل",
    "c_details": "تفاصيل ",
    "c_action": "عمل ",
    "c_actions": "أعمال ",
    "c_mapid": "عنوان او رقم الخريطة ",
    "c_zoom": "مستوى التكبير ",
    "c_zoom_data": "تكبير البيانات بيانات المتجه ",
    "c_vector_data": "البيانات المتجهة ",
    "c_vector_style": "اسلوب متجه",
    "c_portrait": "صورة للوجه  / لوحة ",
    "c_landscape": "المناظر الطبيعية ",
    "c_tools": "أدوات ",
    "c_required": "جعل المطلوب ",
    "c_not_required": "عدم جعل المطلوب ",
    "c_del_sel": "حذف المختار ",
    "c_print": "طباعة ",
    "c_repeat": "تكرار ",
    "c_scheduled": "المقرر ",
    "c_t_c": "الأحكام والشروط ",
    "c_agree": "أنا أوافق على ",
    "c_select": "إختيار ",
    "c_status": "الحالة ",
    "c_coords": "احداثيات",
    "c_task": "مهمة  /اختبار / عمل",
    "c_rec": "(موصى به)",
    "c_source": "مصدر ",
    "c_show": "عرض ",
    "c_hide": "إخفاء ",
    "c_totals": "المجموع ",
    "c_instances": "الحالات ",
    "c_device": "جهاز  / أداة ",
    "c_success": "نجاح ",
    "c_errors": "أخطاء ",
    "c_error": "خطأ ",
    "c_lt": "الوقت المحلي ",
    "c_location": "الموقع ",
    "c_ident": "المعرّّف",
    "c_version": "الإصدار ",
    "c_deleted": "تم حذفه",
    "c_yes": "نعم ",
    "c_no": "كلا ",
    "c_reason": "السبب ",
    "c_complete": "إكتمال ",
    "c_record": "تسجيل ",
    "c_records": "تسجيلات ",
    "c_of": "من ",
    "c_media": "وسائل الإعلام ",
    "c_changes": "التغييرات ",
    "c_calc": "عمليات حسابية ",
    "c_trans": "الترجمة ",
    "c_org": "منظمة ",
    "c_orgs": "منظمات",
    "c_all_s": "كل الاستطلاعات ",
    "c_event": "حدث ",
    "c_note": "ملاحظة  / ملحوظة ",
    "c_server": "الخادم ",
    "c_cols": "الأعمدة ",
    "c_add": "إضافة  / جمع",
    "c_create": "خلق  / أبدع ",
    "c_imp_xls": "جدول الاستيراد ",
    "c_xlstype": "نموذج اكسل ",
    "c_roles": "وظائف ",
    "c_s_roles": "مسح الأدوار ",
    "c_role": "وظيفة ",
    "c_id": "الهوية الشخصية ",
    "c_insert": "إدراج ",
    "c_tz": "وحدة زمنية ",
    "c_undef": "غير معرف ",
    "c_license": "رقم الرخصة ",
    "c_in": "في",
    "c_rev": "عكسي",
    "ft": "نوع الملف ",
    "ft_xls": "نموذج XLS ",
    "ft_xls_orig": "ملف XLS الاصلي",
    "ft_xml": "نموذج XML ",
    "ft_codebook": "رمز الكتاب ",
    "ft_pdf": "قالبPDF ",
    "ft_spss": "SPS ملف (SPSS)",
    "tm_s_del": "عرض النماذج المحذوفة ",
    "tm_d_forms": "حذف نماذج ",
    "tm_r_forms": "إستعادة نماذج",
    "tm_e_forms": "محو نماذج ",
    "tm_c_form": "انشاء نموذج ",
    "tm_c_xls": "استخدام محرر جدول البيانات ",
    "tm_g_temp": "تحميل قالب ",
    "tm_g_new": "انشاء نموذج جديد ",
    "tm_g_open": "فتح نموذج ",
    "tm_g_temp_i1": "تحميل قالب لإنشاء نموذج جديد على جهاز الكمبيوتر الشخصي الخاص بك. عند الانتهاء، تحميله على الخادم عن طريق النقر على زر التحميل أدناه. سوف تحتاج أولا لتحديد ملف XLS تحتوي على النموذج قمت بإنشائها وإعطائه اسما.",
    "tm_g_temp_i3": "دليل مرجعي ",
    "tm_ul_f": "تحميل جدول البيانات ",
    "tm_si": "مسح تحديد المعرف",
    "tm_up": "تحميل قالب ",
    "tm_add_for": "إضافة للأمام ",
    "tm_ref_f": "تحديث قائمة النماذج ",
    "a_exp_title": "نتائج التصدير ",
    "a_exp_leg1": "اختر الخادم",
    "a_exp_leg2": "تنسيق الإخراج ",
    "a_exp_notes": "ملاحظات التصدير ",
    "a_exp_split": "تقسيم خطوط الطول/العرض ",
    "a_exp_merge": "ضغط المضاعفات المختارة ",
    "a_sel_ways": "تحديد الطرق (ان وجدت)",
    "a_sel_forms": "تحديد نماذج لتشمل ",
    "a_sel_model": "تحرير نموذج الخادم",
    "a_type": "نوع الرسم البياني ",
    "a_showon": "عرض على ",
    "a_ss": "اختر الخادم",
    "a_sq": "Select question",
    "a_gb": "Group by",
    "a_ts": "Time series",
    "a_g_gps": "GPS coordinates within region",
    "a_fbv": "Filter by value",
    "a_from_date": "From date",
    "a_to_date": "To date",
    "a_fq": "Filter question",
    "a_res": "Please provide a reason",
    "a_mb": "Marked Bad",
    "a_cm": "Cluster Members",
    "a_dv": "Show Details",
    "a_rd": "Report Definition",
    "a_embed": "Embed Images in Excel File",
    "a_hxl": "HXL",
    "msg_wait": "Waiting for a response from the server. Please try again in a few seconds",
    "msg_reason": "Please provide a reason:",
    "msg_sel_survey": "You must select a survey",
    "msg_sel_dates": "From date is greater than To date",
    "msg_sel_q": "You must select a question to show on a graph",
    "msg_val_prot": "Protocol (http:// or https://) must be specified with the hostname",
    "msg_val_p": "A project must be selected for this form",
    "msg_val_rf": "You must select a remote form",
    "msg_val_rh": "You must select a remote host",
    "msg_val_u_id": "You must specify a user id",
    "msg_val_pass": "You must specify a password",
    "msg_nv": "Please specify a new value",
    "msg_val_nm": "Name is required",
    "msg_val_file": "A file must be selected",
    "msg_val_let": "Name must start with a letter or underscore",
    "msg_add_notification": "Add Notification",
    "msg_edit_notification": "Edit Notification",
    "msg_add_map": "Add Map",
    "msg_edit_map": "Edit Map",
    "msg_sel_form": "Select Form:",
    "msg_sel_media": "Select Media Question:",
    "msg_err_save": "Error: Save failed:",
    "msg_err_del": "Error: Delete failed:",
    "msg_err_cr": "Error: Create failed:",
    "msg_err_upd": "Error: Update failed:",
    "msg_err_res": "Error: Restore failed:",
    "msg_err_block": "Error: Block failed:",
    "msg_err_get_f": "Error: Get forms failed:",
    "msg_err_get_r": "Error: Get roles failed",
    "msg_err_get_a": "Error: Get alerts failed",
    "msg_err_get_q": "Error: Get questions failed",
    "msg_upd": "Update Succeeded",
    "msg_err_nc": "Name cannot include a comma",
    "msg_err_wait": "Either waiting for the server or there are no surveys in this project to assign to a user. If the project does have surveys then try again in a few seconds",
    "msg_err_cert": "Remote server does not have a signed certificate, try using http:// instead of https://",
    "msg_no_edit_rep": "You cannot edit a record that has been replaced by another record",
    "msg_confirm_del": "Are you sure you want to delete",
    "msg_confirm_tasks": "this group and all of its tasks?",
    "msg_del_r": "Are you sure you want to delete these regions?",
    "msg_erase": "Are you sure you want to permanently erase these surveys and all of their data?",
    "msg_restore": "Are you sure you want to restore these surveys?",
    "msg_del_recs": "There are %s1 data rows submitted for %s2. Are you sure you want to delete this data?",
    "msg_del_s": "Are you sure you want to delete these surveys?",
    "msg_del_data": "Are you sure you want to delete all the data in this survey?",
    "msg_del_data2": "Are you really sure?",
    "msg_del_rep": "Are you sure you want to delete this report?",
    "msg_del_users": "Are you sure you want to delete these users?",
    "msg_del_projects": "Are you sure you want to delete these projects?",
    "msg_del_roles": "Are you sure you want to delete these roles?",
    "msg_del_orgs": "Are you sure you want to delete these organisations?",
    "msg_del_q": "Are you sure you want to delete this question?",
    "msg_del_cl": "Are you sure you want to delete this choice list?",
    "msg_del_c": "Are you sure you want to delete this choice?",
    "msg_n_v": "Not valid",
    "msg_u_f": "Error upload failed",
    "msg_u_nt": "No nfc tags found",
    "msg_csv": "Only CSV files and Zip files containing CSV and media files are allowed",
    "msg_inv_email": "Not a valid email address",
    "msg_cs": "Click to filter or sort on this column",
    "msg_nrf": "No results forwarded to another server",
    "msg_saf": "Select a form to view the users that have downloaded that form",
    "msg_nf": "No forms",
    "msg_ns": "No Submissions",
    "msg_us": "Unknown Source",
    "msg_tg_ns": "Task group not selected",
    "msg_no_roles": "There are no enabled roles. Hence there are no restrictions on access",
    "msg_has_roles": "Only users who have one of the following enabled roles are allowed access",
    "msg_one_f": "At least one form must be selected",
    "msg_one_f2": "A form must be selected",
    "msg_embed": "The excel type must be xls or xlsx to embed images",
    "msg_pss": "Please select a survey",
    "msg_nm": "No images, video, audio found",
    "msg_pr": "Password has been reset",
    "msg_es": "Email has been sent to",
    "msg_refresh": "You have made some changes and not saved them, are you sure you want to refresh?",
    "msg_leave": "You have made some changes and not saved them, are you sure you want to leave?",
    "e_b_e": "Base on existing form",
    "e_s_r": "Store results in shared table",
    "t_complete": "Show Completed Tasks",
    "t_show": "Show tasks for:",
    "t_assign": "Assign User",
    "t_add_group": "Add Task Group",
    "t_del_group": "Delete Task Group",
    "t_lt_file": "Load Tasks From File",
    "t_choose_user": "Choose the user to assign to the selected tasks",
    "t_ce": "Clear Existing Tasks",
    "t_ce_warn": "This will clear all the existing data in the survey. Are you sure you want to do this?",
    "t_ceg": "Create Empty Task Group",
    "t_cfe": "Create from existing data",
    "t_ep": "Existing Project",
    "t_es": "Existing Survey",
    "t_ec": "Existing Choice",
    "t_et": "Existing Text",
    "t_nt": "New Text",
    "t_ns": "New Survey",
    "t_ft": "Filter Tasks",
    "t_fq": "Filter by Question",
    "t_so": "Selected Option",
    "t_sn": "Set Numeric Value",
    "t_st": "Set Text Value",
    "t_ue": "Update Existing Results",
    "t_ap": "Address Parameters",
    "t_nfc": "NFC or Location",
    "t_assigned": "Assigned",
    "t_fl": "File Loaded",
    "t_efnl": "Error file not loaded",
    "t_ens": "Error not saved",
    "t_add_tasks": "Click on the map where you want to add new tasks. When finished click on 'Save Tasks' button",
    "t_add_task": "Add Task",
    "t_edit_task": "Edit Task",
    "t_add_tasks2": "Add Tasks",
    "t_save_tasks": "Save Tasks",
    "t_tasks_only": "Tasks Only",
    "t_tg": "Task Group",
    "t_tasks": "المهام",
    "t_id": "Initial Data",
    "t_n_s": "Tasks without start time",
    "t_drag": "Drag a task and drop onto calendar",
    "t_g": "Guidance",
    "t_ass_done": "Have you completed this assignment?",
    "e_u_err": "Form Upload Error",
    "e_u_exists": "exists in project",
    "e_h_rename": "Change the name of the form or delete the old form",
    "e_u_sm_no_list": "select_multiple question without list name",
    "e_h_sm_no_list": "Check the survey sheet. Make sure you have specified a list name for all the select_multiple questions",
    "e_u_so_no_list": "select_one question without list name",
    "e_h_so_no_list": "Check the survey sheet. Make sure you have specified a list name for all the select_one questions",
    "e_unknown": "Unknown error",
    "e_get_help": "Contact the help desk",
    "e_calc": "Calculation error",
    "e_h_calc1": "Check the 'calculation' column for an invalid formula (A valid formula results in either true or false)",
    "e_h_calc2": "Otherwise check the 'relevant' column for a formula that does not result in a true or false result",
    "e_inv_f": "Invalid Function",
    "e_h_f1": "Check for capital letters, all letters should be lower case",
    "e_h_f2": "Check for spelling mistakes in the name of the function",
    "e_val": "Validation error",
    "e_circ": "Check for circular references",
    "e_in_q": "in question",
    "e_h_c1": "A 'relevant' statement for question is potentially referring to  itself instead of referring to another question",
    "e_h_c2": "Relevant statements are evaluated before a question is asked so they cannot refer to their own questions",
    "e_brackets": "Mismatched brackets in function",
    "e_text": "Error with the following text:",
    "r_o_n": "Organisation Name",
    "r_y_n": "Your Name",
    "r_y_e": "Your Email",
    "r_y_o": "Organisation Website",
    "r_f": "Registration Form",
    "mon_l200": "(last 200)",
    "mon_gtb": "Group Totals by",
    "mon_nl": "Not Loaded",
    "mon_dup": "Duplicates",
    "mon_att": "Extra Attachments",
    "mon_sa": "Show As",
    "mon_zoom_grid": "Zoom to Grids",
    "mon_show_grid": "Show Grids",
    "mon_clear_grid": "Clear Grids",
    "mon_create_grid": "Create Grid",
    "mon_del_grid": "Delete Grids",
    "mon_sel_layer": "Select a layer to add to the map as an overlay",
    "mon_c_reg": "Create a new region",
    "mon_c_reg_i": "Enter a name for the region and the width of each cell in meters. Click on the map to set the centre of one of the cells. Press the \"shift\"button and drag the mouse to set the bounds.",
    "mon_name_cond": "(lowercase, no spaces or numbers)",
    "mon_cw": "Cell Width (in Meters. greater than 10)",
    "mon_centre": "Centre: (click on map)",
    "mon_bounds": "Boundary: (click and drag on map while pressing shift key)",
    "mon_sel_del": "Select the regions that you want to delete",
    "mon_ud": "Upload Date",
    "mon_pi": "Phone Identifier",
    "mon_fr": "Failure Reason",
    "mon_file": "File with raw results",
    "an_auth": "Author",
    "an_published": "Published",
    "an_dr": "Date Range",
    "an_csel": "Clear Selection",
    "Upload Time": "تحميل ",
    "_start": "Start Time",
    "_end": "End Time",
    "percent": "Percent",
    "count": "Count",
    "none": "لا شيء ",
    "average": "Average",
    "wf_sig": "Signature",
    "ed_qt": "Question Text",
    "ed_ct": "Choice Text",
    "ed_qh": "Question Hint",
    "ed_cl": "Choice List",
    "ed_appearance": "Appearance",
    "ed_con": "Constraint",
    "ed_con_msg": "Constraint Message",
    "ed_rel": "Relevant",
    "ed_req": "Required",
    "ed_ap": "Auto play",
    "ed_at": "GPS Accuracy Threshold",
    "ed_ls": "Linked Survey",
    "ed_ro": "Read Only",
    "ed_ls_add": "Add link",
    "ed_l": "Linked",
    "ed_nl": "Not Linked",
    "ed_r_msg": "Required Text Message",
    "ed_o_o_g": "Only one geometry question can be added to a form",
    "ed_hrk": "Unique Key",
    "ed_csv": "CSV File",
    "ed_c_s": "Source of Choices",
    "ed_i_c": "Created",
    "ed_st": "Shared Table",
    "ed_ld": "Allow Loading data from file",
    "ed_i_bo": "Based On",
    "ed_i_tn": "Table Names",
    "ed_tlf": "Top Level Form",
    "ed_namedia": "Media cannot be used with this question",
    "mf_fd": "Form Data",
    "mf_md": "Management Data",
    "mf_sc": "Visible Columns",
    "mf_sc_i": "Select the columns that you want to see in the table then press the 'Apply' button. You can then sort on these columns",
    "mf_qr": "QR Columns",
    "mf_bc_i": "Select the columns that you want to see as barcodes in the table and in reports",
    "mf_st": "Submission Tracking",
    "mf_gr": "Get related",
    "mf_of": "Oversight Form",
    "mf_no": "There are no oversight forms. They can be added in the \"Available Oversight Forms\" tab",
    "mf_sel": "Select the form that you want to manage and the oversight form that you want to manage it with.",
    "mf_ao": "Available oversight forms",
    "mf_mf": "Managed forms",
    "lo_back": "رجوع / عودة ",
    "lo_out": "You are logged out of",
    "lo_lo": "Logged Out",
    "u_show_u": "Show users with security group",
    "u_show_p": "Show users in project",
    "u_add": "Add User",
    "u_del": "Delete User",
    "u_mv": "Move To Organisation",
    "u_add_p": "Add Project",
    "u_del_p": "Delete Project",
    "u_add_o": "Add Organisation",
    "u_del_o": "Delete Organisation",
    "u_add_r": "Add Role",
    "u_edit_r": "Edit Role",
    "u_del_r": "Delete Role",
    "u_det": "User Details",
    "u_ident": "Ident (lowercase, no spaces or an email address)",
    "u_email": "Send email to new user",
    "u_set_p": "Specify password",
    "u_sg": "Security Groups",
    "u_det_p": "Project Details",
    "u_det_ur": "User Role Details",
    "u_det_o": "Organisation Details",
    "u_det_o_rep": "Report Publishing Options",
    "u_det_o_ft": "FieldTask Options",
    "u_ft_del": "Delete submitted results from the phone",
    "u_ft_ld": "Send location data on path of user",
    "u_det_o_email": "Email Options",
    "u_det_o_other": "Other Options",
    "u_other_edit": "Allow editing of results",
    "u_mb_k": "Mapbox Key",
    "u_g_k": "Google Maps Key",
    "u_smtp": "Smtp Host",
    "u_e_dom": "Email Domain",
    "u_e_nm": "Email user name",
    "u_e_p": "Email password",
    "u_e_port": "Email Server port",
    "u_h_e": "Email to get Help",
    "u_rap": "Restrict access",
    "u_rap_d": "Administrators will be able to assign the selected users only to this project",
    "u_chg": "Changed by",
    "u_usage": "Usage Report",
    "br_ci": "Case Insensitive",
    "br_exact": "Exact Match",
    "br_cc": "Select the columns that you want to test for similarities in the data. For each column that you want to test you can select a function to broaden the range of values that will match.",
    "br_s": "Search",
    "br_sdx": "Soundex",
    "sr_res": "Images Video Audio and CSV Files",
    "sr_nfc": "NFC Tags",
    "ar_af": "Add Files",
    "sr_g": "Group",
    "sr_fn": "File Name",
    "sr_m_ph": "Enter a name for your map",
    "sr_m_d": "Enter a description for this map (optional)",
    "sr_m_mb": "For Mapbox this identifies the map, for example: mapbox.light",
    "sr_cr": "Custom Reports",
    "ar": "Arabic",
    "en": "English",
    "fr": "French",
    "hi": "Hindi",
    "pt": "Portuguese",
    "es": "Spanish",
    "n_wf": "Web Form",
    "n_pdfp": "PDF (Portrait)",
    "n_pdfl": "PDF (Landscape)",
    "n_eq": "Email Question",
    "n_share": "Get link",
    "ro_fr": "Filter rows",
    "ro_fc": "Filter columns",
    "ro_fr_rule": "Rows to be shown",
    "ro_aq": "Available Questions",
    "ro_fr_i": "Enter a rule that determines which rows will be shown for this role. Enclose question names in ${...}. Enclose text in single quotes. Make sure there are spaces between the question names and operators such as =.<br/>Example 1: ${region} = 'northern'<br/>Example 2: ${age} > 16. If no rule is specified then all rows will be shown.",
    "ro_fc_i": "Select the columns to show with this filter. If no columns are selected then all columns will be shown.",
    "i_sec": "second ago",
    "i_secs": "seconds ago",
    "i_min": "minute ago",
    "i_mins": "minutes ago",
    "i_hour": "hour ago",
    "i_hours": "hours ago",
    "i_day": "day ago",
    "i_days": "days ago",
    "d_sound": "Play sound on new alert",
    "d_rep_def_freq": "Frequency Report",
    "bar": "Bar Chart",
    "pie": "Pie Chart",
    "line": "Line Chart",
    "wordcloud": "Word Cloud",
    "length": "Count",
    "d_qtr": "25%",
    "d_half": "50%",
    "d_3qtr": "75%",
    "d_full": "100%",
    "d_sec": "Seconds",
    "d_min": "Minutes",
    "d_hour": "Hours",
    "d_c_day": "Count by day",
    "d_c_month": "Coount by month",
    "d_c_year": "Count by year",
    "rev_upd_diff": "Update a different question to the source question",
    "rev_q_upd": "Question to update",
    "rev_text": "Text",
    "rev_upd": "Update",
    "rev_upd_t": "Update target question",
    "rev_upd_text": "Update Text Questions",
    "rev_rt": "Replace text",
    "rev_rc": "records with choice",
    "rev_fq": "from question",
    "rev_rw": "records with",
    "rev_rdm": "Review Data Modifications",
    "rev_ci": "Change Id",
    "rev_rb": "Reversed By",
    "rev_rcn": "Reverse Change Number",
    "rev_det": "Details for change number",
    "rev_cq": "Changed Question",
    "rev_sc": "Selcted Choice",
    "rev_usc": "Un-Selected Choice"
});